const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const C=require('../../browser-companion/core.js');
const source=fs.readFileSync(path.join(__dirname,'../../browser-companion/background.js'),'utf8');
function worker(){const db={dashboard:{url:'https://stratedge.example/application-bot/',origin:'https://stratedge.example'}};const listeners={};const tabs=[];const clone=v=>JSON.parse(JSON.stringify(v));let permitted=true;const event=n=>({addListener:f=>listeners[n]=f});const chrome={storage:{local:{setAccessLevel:async()=>{},get:async keys=>Object.fromEntries(keys.filter(k=>k in db).map(k=>[k,clone(db[k])])),set:async values=>Object.assign(db,clone(values))}},permissions:{contains:async()=>permitted},scripting:{registerContentScripts:async()=>{},unregisterContentScripts:async()=>{},executeScript:async()=>[]},alarms:{create:async()=>{},clear:async()=>{},onAlarm:event('alarm')},tabs:{query:async()=>[],sendMessage:async()=>{},create:async({url})=>{const t={id:tabs.length+1,url,status:'loading'};tabs.push(t);return t;},get:async id=>tabs.find(t=>t.id===id),onUpdated:event('tabUpdate'),onRemoved:event('tabRemove')},runtime:{id:'unit',getURL:s=>'chrome-extension://unit/'+s,onStartup:event('startup'),onMessage:event('message'),onMessageExternal:event('external')}};const context={chrome,ApplyCore:C,importScripts:()=>{},URL,Date,console,setTimeout};vm.createContext(context);vm.runInContext(source,context);return {db,tabs,listeners,deny(){permitted=false;},message(message,sender={id:'unit',tab:{id:100,url:'https://stratedge.example/application-bot/'}}){return new Promise(resolve=>listeners.message(message,sender,resolve));},external(message,sender){return new Promise(resolve=>listeners.external(message,sender,resolve));}};}
const payload=()=>({profile:{fullName:'Alex Example',email:'alex@example.com',skills:'BGP'},resume:null,settings:{mode:'review',dailyLimit:5,minScore:40,allowedHosts:[]},jobs:[C.makeJob({url:'https://careers.example.com/jobs/1',title:'Network Engineer',company:'Example',description:'BGP',approved:true})]});
test('Companion refuses messages from an unconnected origin',async()=>{const w=worker();const r=await w.message({action:'DASHBOARD_PING'},{id:'unit',tab:{url:'https://other.example/'}});assert.match(r.error,/not connected/);});
test('Companion RUN opens an approved employer job and persists loading state',async()=>{const w=worker();const r=await w.message({action:'DASHBOARD_RUN',payload:payload()});assert.equal(r.result.started,true);assert.equal(w.tabs.length,1);assert.equal(w.db.engine.current.stage,'loading');assert.equal(w.db.engine.current.attempted,false);});
test('Missing optional host permission opens the allow-this-site page instead of the job',async()=>{const w=worker();w.deny();const r=await w.message({action:'DASHBOARD_RUN',payload:payload()});assert.match(r.error,/Allow the companion on careers\.example\.com/);assert.equal(w.tabs.length,1);assert.match(w.tabs[0].url,/^chrome-extension:\/\/unit\/grant\.html\?u=/);assert.ok(!w.db.engine||w.db.engine.running===false);});
test('A restricted portal cannot be run through a direct extension message',async()=>{const w=worker();const p=payload();p.jobs[0].url='https://www.dice.com/jobs/1';const r=await w.message({action:'DASHBOARD_RUN',payload:p});assert.match(r.error,/manual/);assert.equal(w.tabs.length,0);});
test('Pause persists a review status and stops subsequent jobs',async()=>{const w=worker();await w.message({action:'DASHBOARD_RUN',payload:payload()});const r=await w.message({action:'DASHBOARD_STOP'});assert.equal(r.result.stopped,true);assert.equal(w.db.engine.running,false);assert.equal(w.db.engine.current,null);assert.equal(Object.values(w.db.updates)[0].status,'review');});
test('Browser restart never silently retries an in-flight submission',async()=>{const w=worker();await w.message({action:'DASHBOARD_RUN',payload:payload()});w.db.engine.current.attempted=true;await w.listeners.startup();assert.equal(w.db.engine.running,false);assert.equal(w.db.engine.current,null);assert.equal(Object.values(w.db.updates)[0].status,'uncertain');});
test('Already submitted and uncertain statuses reject rerun requests',async()=>{for(const status of ['submitted','uncertain']){const w=worker();const p=payload();p.jobs[0].status=status;const r=await w.message({action:'DASHBOARD_RUN',payload:p});assert.match(r.error,/cannot be rerun/);assert.equal(w.tabs.length,0);}});
test('v83: the direct path refuses localhost, plain http, other ports, mail/control-panel subdomains and other sites',async()=>{for(const origin of ['http://localhost:3000','http://127.0.0.1:9412','http://stratedgeitconsulting.com','https://stratedgeitconsulting.com:8443','https://webmail.stratedgeitconsulting.com','https://cpanel.stratedgeitconsulting.com','https://a.b.stratedgeitconsulting.com','https://stratedgeitconsulting.com.evil.example','https://evil.example']){const w=worker();const r=await w.external({action:'SYNC',payload:{profile:{fullName:'X',email:'x@x.test'}}},{origin,url:origin+'/'});assert.equal(r.error,'Unknown sender.',origin);assert.equal(w.db.synced,undefined,origin);w.db.updates={j1:{id:'j1',status:'submitted',note:'n',updatedAt:'T'}};const p=await w.external({action:'PING'},{origin,url:origin+'/'});assert.equal(p.error,'Unknown sender.',origin);const a=await w.external({action:'ACK',ids:['j1']},{origin,url:origin+'/'});assert.equal(a.error,'Unknown sender.',origin);assert.ok(w.db.updates.j1,origin);}});
test('v83: the portal, www and a workspace subdomain still use the direct path',async()=>{for(const origin of ['https://stratedgeitconsulting.com','https://www.stratedgeitconsulting.com','https://acme.stratedgeitconsulting.com']){const w=worker();const p=await w.external({action:'PING'},{origin,url:origin+'/#/portal/appbot'});assert.ok(p.result&&p.result.version!==undefined,origin);}const w=worker();const r=await w.external({action:'SYNC',payload:{profile:{fullName:'Alex Example',email:'alex@example.com'}}},{origin:'https://acme.stratedgeitconsulting.com',url:'https://acme.stratedgeitconsulting.com/'});assert.equal(r.result.synced,true);assert.equal(w.db.synced.portal,'https://acme.stratedgeitconsulting.com/#/portal/appbot');});
test('v83: the direct ACK forgets saved reports but keeps one that changed after the poll',async()=>{const w=worker();w.db.updates={a:{id:'a',status:'review',updatedAt:'T1'},b:{id:'b',status:'error',updatedAt:'T3'}};const r=await w.external({action:'ACK',ids:['a','b'],at:{a:'T1',b:'T2'}},{origin:'https://stratedgeitconsulting.com',url:'https://stratedgeitconsulting.com/'});assert.equal(r.result.left,1);assert.equal(w.db.updates.a,undefined);assert.ok(w.db.updates.b);});
test('v83: the page bridge ACK (DASHBOARD_ACK) forgets saved reports, only from the connected dashboard',async()=>{const w=worker();w.db.updates={a:{id:'a',status:'review',updatedAt:'T1'},b:{id:'b',status:'error',updatedAt:'T3'}};const bad=await w.message({action:'DASHBOARD_ACK',payload:{ids:['a'],at:{a:'T1'}}},{id:'unit',tab:{url:'https://other.example/'}});assert.match(bad.error,/not connected/);assert.ok(w.db.updates.a);const r=await w.message({action:'DASHBOARD_ACK',payload:{ids:['a','b'],at:{a:'T1',b:'T2'}}});assert.equal(r.result.left,1);assert.equal(w.db.updates.a,undefined);assert.ok(w.db.updates.b);const p=await w.message({action:'DASHBOARD_PING'});assert.equal(p.result.updates.map(u=>u.id).join(','),'b');});
