const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const C=require('../../browser-companion/core.js');
const source=fs.readFileSync(path.join(__dirname,'../../browser-companion/background.js'),'utf8');
function worker(){const db={dashboard:{url:'https://stratedge.example/application-bot/',origin:'https://stratedge.example'}};const listeners={};const tabs=[];const clone=v=>JSON.parse(JSON.stringify(v));let permitted=true;const event=n=>({addListener:f=>listeners[n]=f});const chrome={storage:{local:{setAccessLevel:async()=>{},get:async keys=>Object.fromEntries(keys.filter(k=>k in db).map(k=>[k,clone(db[k])])),set:async values=>Object.assign(db,clone(values))}},permissions:{contains:async()=>permitted},scripting:{registerContentScripts:async()=>{},unregisterContentScripts:async()=>{},executeScript:async()=>[]},alarms:{create:async()=>{},clear:async()=>{},onAlarm:event('alarm')},tabs:{query:async()=>[],sendMessage:async()=>{},create:async({url})=>{const t={id:tabs.length+1,url,status:'loading'};tabs.push(t);return t;},get:async id=>tabs.find(t=>t.id===id),onUpdated:event('tabUpdate'),onRemoved:event('tabRemove')},runtime:{id:'unit',getURL:s=>'chrome-extension://unit/'+s,onStartup:event('startup'),onMessage:event('message')}};const context={chrome,ApplyCore:C,importScripts:()=>{},URL,Date,console,setTimeout};vm.createContext(context);vm.runInContext(source,context);return {db,tabs,listeners,deny(){permitted=false;},message(message,sender={id:'unit',tab:{id:100,url:'https://stratedge.example/application-bot/'}}){return new Promise(resolve=>listeners.message(message,sender,resolve));}};}
const payload=()=>({profile:{fullName:'Alex Example',email:'alex@example.com',skills:'BGP'},resume:null,settings:{mode:'review',dailyLimit:5,minScore:40,allowedHosts:[]},jobs:[C.makeJob({url:'https://careers.example.com/jobs/1',title:'Network Engineer',company:'Example',description:'BGP',approved:true})]});
test('Companion refuses messages from an unconnected origin',async()=>{const w=worker();const r=await w.message({action:'DASHBOARD_PING'},{id:'unit',tab:{url:'https://other.example/'}});assert.match(r.error,/not connected/);});
test('Companion RUN opens an approved employer job and persists loading state',async()=>{const w=worker();const r=await w.message({action:'DASHBOARD_RUN',payload:payload()});assert.equal(r.result.started,true);assert.equal(w.tabs.length,1);assert.equal(w.db.engine.current.stage,'loading');assert.equal(w.db.engine.current.attempted,false);});
test('Missing optional host permission opens the allow-this-site page instead of the job',async()=>{const w=worker();w.deny();const r=await w.message({action:'DASHBOARD_RUN',payload:payload()});assert.match(r.error,/Allow the companion on careers\.example\.com/);assert.equal(w.tabs.length,1);assert.match(w.tabs[0].url,/^chrome-extension:\/\/unit\/grant\.html\?u=/);assert.ok(!w.db.engine||w.db.engine.running===false);});
test('A restricted portal cannot be run through a direct extension message',async()=>{const w=worker();const p=payload();p.jobs[0].url='https://www.dice.com/jobs/1';const r=await w.message({action:'DASHBOARD_RUN',payload:p});assert.match(r.error,/manual/);assert.equal(w.tabs.length,0);});
test('Pause persists a review status and stops subsequent jobs',async()=>{const w=worker();await w.message({action:'DASHBOARD_RUN',payload:payload()});const r=await w.message({action:'DASHBOARD_STOP'});assert.equal(r.result.stopped,true);assert.equal(w.db.engine.running,false);assert.equal(w.db.engine.current,null);assert.equal(Object.values(w.db.updates)[0].status,'review');});
test('Browser restart never silently retries an in-flight submission',async()=>{const w=worker();await w.message({action:'DASHBOARD_RUN',payload:payload()});w.db.engine.current.attempted=true;await w.listeners.startup();assert.equal(w.db.engine.running,false);assert.equal(w.db.engine.current,null);assert.equal(Object.values(w.db.updates)[0].status,'uncertain');});
test('Already submitted and uncertain statuses reject rerun requests',async()=>{for(const status of ['submitted','uncertain']){const w=worker();const p=payload();p.jobs[0].status=status;const r=await w.message({action:'DASHBOARD_RUN',payload:p});assert.match(r.error,/cannot be rerun/);assert.equal(w.tabs.length,0);}});
