const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const C=require('../../browser-companion/core.js');
const source=fs.readFileSync(path.join(__dirname,'../../browser-companion/form.js'),'utf8');
function fixture(options={}){
  class Input{constructor(name,label,type='text',required=true){Object.assign(this,{name,id:name,labels:[{textContent:label}],type,required,disabled:false,readOnly:false,visible:true,autocomplete:'',placeholder:'',checked:false,_value:'',files:[]});}get value(){return this._value;}set value(v){this._value=String(v);}get validity(){return {valid:!this.required||!!this.value||this.checked};}getClientRects(){return this.visible?[{}]:[];}getAttribute(){return null;}closest(){return null;}dispatchEvent(){}click(){this.checked=!this.checked;}}
  class Select extends Input{};class TextArea extends Input{};
  const fields=[new Input('fullName','Full name *'),new Input('email','Email address *','email')];if(options.unknown)fields.push(new Input('customQuestion','How many years of BGP experience?','number'));if(options.consent)fields.push(new Input('policy','I agree to the privacy policy','checkbox'));if(options.prefilled)fields[0].value='Another Person';let clicks=0;
  const body={innerText:'Job application'};const button={visible:true,disabled:false,innerText:options.next?'Continue':'Submit application',getClientRects(){return [{}];},click(){clicks++;form.visible=false;body.innerText='Application submitted successfully';}};
  const form={visible:true,action:'https://careers.example.com/apply',get innerText(){return 'Job application '+fields.map(e=>e.labels[0].textContent).join(' ');},getClientRects(){return this.visible?[{}]:[];},querySelectorAll(selector){if(selector==='input,select,textarea')return fields;if(selector==='button,input[type=submit]')return [button];if(selector==='input[type=radio]')return [];return [];}};
  const document={forms:[form],body,title:'Job application',querySelectorAll(selector){if(selector==='h1,h2')return [{textContent:'Job application'}];if(selector==='input[type=password]'&&options.login)return [new Input('password','Password','password')];return [];}};
  const context={ApplyCore:C,document,location:{href:'https://careers.example.com/apply'},getComputedStyle:e=>({visibility:e.visible?'visible':'hidden',display:e.visible?'block':'none'}),HTMLInputElement:Input,HTMLSelectElement:Select,HTMLTextAreaElement:TextArea,Event:class {},setTimeout:fn=>{fn();return 1;},console};vm.createContext(context);vm.runInContext(source,context);return {bot:context.ApplyBot,fields,form,body,clicks:()=>clicks};
}
const profile={fullName:'Alex Example',email:'alex@example.com',yearsExperience:'8.5',answers:{}};
test('Standard application fields fill and an unchanged valid form can submit',async()=>{const f=fixture();const plan=await f.bot.fill(profile,null);assert.equal(plan.filled,2);assert.deepEqual(Array.from(plan.missing),[]);assert.equal(f.bot.confirmation().confirmed,false);assert.equal(f.bot.commit(plan).clicked,true);assert.equal(f.clicks(),1);assert.equal(f.bot.confirmation().confirmed,true);});
test('An unknown technical experience question blocks automatic submission',async()=>{const f=fixture({unknown:true});const plan=await f.bot.fill(profile,null);assert.match(plan.missing.join(' '),/BGP/);assert.equal(f.fields[2].value,'');assert.equal(f.bot.commit(plan).clicked,false);assert.equal(f.clicks(),0);});
test('Required consent stays unchecked unless an exact saved answer exists',async()=>{const f=fixture({consent:true});const plan=await f.bot.fill(profile,null);assert.equal(f.fields[2].checked,false);assert.ok(plan.missing.length);assert.equal(f.bot.commit(plan).clicked,false);});
test('An existing answer that differs from the profile is flagged for review',async()=>{const f=fixture({prefilled:true});const plan=await f.bot.fill(profile,null);assert.equal(f.fields[0].value,'Another Person');assert.match(plan.missing.join(' '),/differs/);});
test('Changed form values invalidate a previously prepared submit plan',async()=>{const f=fixture();const plan=await f.bot.fill(profile,null);f.fields[0].value='Changed';assert.equal(f.bot.commit(plan).clicked,false);assert.equal(f.clicks(),0);});
test('Multi-step forms pause instead of clicking Continue',async()=>{const f=fixture({next:true});const plan=await f.bot.fill(profile,null);assert.match(plan.missing.join(' '),/Multi-step/);assert.equal(f.bot.commit(plan).clicked,false);assert.equal(f.clicks(),0);});
test('Visible login fields stop the engine before any autofill',async()=>{const f=fixture({login:true});const plan=await f.bot.fill(profile,null);assert.match(plan.error,/Login/);assert.equal(f.fields[0].value,'');});
test('Receipt text alongside an active form is not a submission confirmation',async()=>{const f=fixture();f.body.innerText='Thank you for applying. Read these instructions before submitting.';assert.equal(f.bot.confirmation().confirmed,false);});
