/* ================= v68 Intelligence & Operations ================= */
const INTEL_TABS = [
  ['overview', 'Command Center'], ['work', 'Recruiter Queue'], ['readiness', 'Readiness Gate'], ['client', 'Client 360'], ['sla', 'Requirement SLA'], ['margin', 'Rate & Margin'],
  ['search', 'Universal Search'], ['candidate', 'Candidate 360'], ['quality', 'Data Quality'], ['deliverability', 'Deliverability'],
  ['integrations', 'Integration Health'], ['replay', 'Integration Replay'], ['analytics', 'Executive Analytics'], ['forecast', 'Forecast'],
  ['grabber', 'Contact Grabber'], ['actions', 'AI Actions'], ['ai', 'AI & Automation'], ['bulk', 'Bulk Actions']
];
const intelNum = n => Number(n || 0).toLocaleString();
const intelPct = (a, b) => b > 0 ? Math.round((Number(a || 0) * 1000) / Number(b)) / 10 : 0;
const intelOpenAi = () => window.dispatchEvent(new CustomEvent('se-panel', { detail: 'ai' }));
function IntelMetric({ x }) {
  return html`<a className="intel-metric" href=${x.href || '#'}><span>${x.n}</span><b>${intelNum(x.v)}</b></a>`;
}
function IntelAlert({ x }) {
  return html`<a className=${'intel-alert ' + (x.sev || '')} href=${x.href || '#'}><span className="intel-dot"></span><span><b>${x.title}</b><small>${x.detail}</small></span></a>`;
}
function IntelBar({ n, v, total }) {
  const p = total > 0 ? Math.max(2, Math.min(100, Number(v || 0) * 100 / total)) : 0;
  return html`<div className="intel-bar"><div><span>${n}</span><b>${intelNum(v)}</b></div><i><em style=${{ width: p + '%' }}></em></i></div>`;
}
function IntelCapabilities({ rows }) {
  return html`<div className="intel-cap-grid">${(rows || []).map(x => html`<a className="intel-cap" href=${x.href || '#'} key=${x.id}>
    <span className="intel-cap-no">${x.id}</span><span><b>${x.n}</b><small>${x.d}</small></span><${Chip} s="ok">Live<//>
  </a>`)}</div>`;
}
function IntelOverview({ d, reload }) {
  return html`<div className="stack">
    <section className="panel intel-hero"><div className="ph-row"><div><div className="eyebrow">v76 Enterprise Automation & Control</div><h2 className="ph">One operating view across StratEdge</h2><p className="muted">Recruiting, clients, submission readiness, SLAs, deliverability, integrations, approvals and forecasting in one exception-first workspace.</p></div><div className="actions"><button className="btn ghost" onClick=${reload}><${Icon} n="refresh" />Refresh</button><button className="btn" onClick=${intelOpenAi}><${AiMark} size=${16}/>Ask StratEdge AI</button></div></div>
      <div className="intel-metrics">${(d.metrics || []).map(x => html`<${IntelMetric} x=${x} key=${x.k}/>` )}</div>
    </section>
    <section id="intel-alerts" className="panel"><div className="ph-row"><h3 className="ph">Needs attention</h3><span className="muted small">Generated from live application data</span></div>
      ${(d.alerts || []).length ? html`<div className="intel-alerts">${d.alerts.map((x,i)=>html`<${IntelAlert} x=${x} key=${i}/>` )}</div>` : html`<${Empty} title="No cross-system exceptions found">The live checks did not find anything urgent in the tracked areas.<//>`}
    </section>
    <section className="panel"><div className="ph-row"><h3 className="ph">20-platform enhancement map</h3><span className="muted small">Each item is connected to an existing system of record.</span></div><${IntelCapabilities} rows=${d.capabilities}/></section>
  </div>`;
}
function IntelSearch() {
  const toast = useToast(); const [q,setQ]=useState(''); const [rows,setRows]=useState([]); const [busy,setBusy]=useState(false);
  const run=async e=>{if(e)e.preventDefault();if(q.trim().length<2)return;setBusy(true);try{const r=await api('intel_search',{q:q.trim()});setRows(r.rows||[]);}catch(e){toast(errText(e),true)}setBusy(false)};
  return html`<section className="panel stack"><div><h2 className="ph">Universal Search</h2><p className="muted">Search people, candidates, requirements, CRM accounts and email contacts together. Results link back to the system that owns the record.</p></div>
    <form className="intel-search" onSubmit=${run}><input value=${q} onInput=${e=>setQ(e.target.value)} placeholder="Name, email, company, skill, requirement…" autofocus/><button className="btn" disabled=${busy||q.trim().length<2}>${busy?'Searching…':'Search everything'}</button></form>
    ${rows.length?html`<div className="intel-results">${rows.map((x,i)=>html`<a className="intel-result" href=${x.href} key=${i}><span className="chip">${x.type}</span><span><b>${x.name}</b><small>${x.sub}</small></span><span>→</span></a>`)}</div>`:html`<${Empty} title="Search across StratEdge">Type at least two characters to search the connected records.<//>`}
  </section>`;
}
function IntelCandidate({ initial }) {
  const toast=useToast();const[id,setId]=useState(initial||'');const[q,setQ]=useState('');const[found,setFound]=useState([]);const[d,setD]=useState(null);const[busy,setBusy]=useState(false);
  const load=async cid=>{if(!cid)return;setBusy(true);try{const r=await api('intel_candidate',{id:cid});setD(r);setId(cid);}catch(e){toast(errText(e),true)}setBusy(false)};
  useEffect(()=>{if(initial)load(initial)},[initial]);
  const find=async e=>{e.preventDefault();if(q.trim().length<2)return;setBusy(true);try{const r=await api('intel_search',{q:q.trim()});setFound((r.rows||[]).filter(x=>x.type==='Candidate'));}catch(e){toast(errText(e),true)}setBusy(false)};
  const c=d&&d.candidate;
  return html`<div className="stack"><section className="panel stack"><div><h2 className="ph">Candidate 360</h2><p className="muted">A single view of candidate identity, stage, communication health, interviews, timeline and matching open requirements.</p></div>
    <form className="intel-search" onSubmit=${find}><input value=${q} onInput=${e=>setQ(e.target.value)} placeholder="Search candidate by name, email or skill"/><button className="btn ghost" disabled=${busy||q.trim().length<2}>Find candidate</button></form>
    ${found.length?html`<div className="intel-picks">${found.slice(0,12).map(x=>html`<button className="btn ghost sm" onClick=${()=>load(x.id)}>${x.name}<small>${x.sub}</small></button>`)}</div>`:null}</section>
    ${c&&html`<section className="panel"><div className="ph-row"><div><h3 className="ph">${c.n||'Unnamed candidate'}</h3><p className="muted">${c.e||'No email'} · ${c.ph||'No phone'} · ${c.loc||'Location not set'}</p></div><div className="actions"><span className="chip">${c.st||'new'}</span><a className="btn ghost sm" href=${'#/portal/admin/ats?c='+encodeURIComponent(c.id)}>Open ATS record</a></div></div>
      <div className="intel-c360-grid"><div><span>Title</span><b>${c.ti||c.jt||'—'}</b></div><div><span>Experience</span><b>${c.exp?c.exp+' years':'—'}</b></div><div><span>Work authorization</span><b>${c.auth||'—'}</b></div><div><span>Source</span><b>${c.src||'—'}</b></div><div><span>Email health</span><b>${(d.health&&d.health.state)||'unknown'}</b><small>${d.health&&d.health.why}</small></div><div><span>Interviews</span><b>${(d.interviews||[]).length}</b></div></div>
      ${c.sk&&html`<div className="intel-skills"><b>Skills</b><p>${c.sk}</p></div>`}
    </section>`}
    ${c&&html`<section className="panel"><div className="ph-row"><h3 className="ph">Best open requirement matches</h3><a className="btn ghost sm" href="#/portal/admin/vreqs">Requirements desk</a></div>
      ${(d.matches||[]).length?html`<div className="intel-match-list">${d.matches.map(x=>html`<div className="intel-match"><div><b>${x.title}</b><small>${x.client||'Client not set'} · ${x.why.join(' · ')}</small></div><strong>${x.score}%</strong></div>`)}</div>`:html`<${Empty} title="No strong open matches">No current requirement scored above the Candidate 360 threshold.<//>`}
    </section>`}
    ${c&&html`<section className="panel"><h3 className="ph">Candidate timeline</h3>${(d.timeline||[]).length?html`<div className="intel-timeline">${[...(d.timeline||[])].reverse().slice(0,30).map((x,i)=>html`<div key=${i}><span>${x.t?fmtTs(x.t):''}</span><b>${x.ev||x.note||'Activity'}</b><small>${x.who||''}</small></div>`)}</div>`:html`<p className="muted">No timeline entries are stored yet.</p>`}</section>`}
  </div>`;
}
function IntelQuality({ d }) {
  const q=d.quality||{};const cards=[['Candidate missing email',q.candidateMissingEmail,'#/portal/admin/ats'],['Duplicate candidate emails',q.candidateDuplicateEmail,'#/portal/admin/ats'],['Stale active candidates',q.candidateStale,'#/portal/admin/ats'],['Incomplete requirements',q.requirementIncomplete,'#/portal/admin/vreqs'],['Stale requirements',q.requirementStale,'#/portal/admin/vreqs'],['Contact cleanup issues',q.contact&&q.contact.n,'#/portal/admin/mail-cleanup']];
  return html`<div className="stack"><section className="panel"><div className="ph-row"><div><h2 className="ph">Data Quality Center</h2><p className="muted">A cross-system queue for missing fields, duplicates, stale records and bad contact data.</p></div><a className="btn" href="#/portal/admin/import">Import with preview</a></div><div className="intel-quality-grid">${cards.map(([n,v,h])=>html`<a href=${h} className=${'intel-quality '+(v?'warn':'ok')}><span>${n}</span><b>${intelNum(v)}</b></a>`)}</div></section>
  <section className="panel"><h3 className="ph">Examples to review</h3>${(q.issues||[]).length?html`<div className="intel-results">${q.issues.map((x,i)=>html`<a className="intel-result" href=${x.href} key=${i}><span className=${'chip '+(x.sev==='high'?'red':'')}>${x.kind}</span><span><b>${x.title}</b><small>${x.name}</small></span><span>→</span></a>`)}</div>`:html`<${Empty} title="No sampled issues">The sampled data-quality checks are clean.<//>`}</section></div>`;
}
function IntelIntegrations({ d }) {
  return html`<section className="panel stack"><div className="ph-row"><div><h2 className="ph">Integration Health Dashboard</h2><p className="muted">One place to see whether the main external services are connected.</p></div><a className="btn" href="#/portal/admin/sources">Portal integrations</a></div><div className="intel-integration-grid">${(d.integrations||[]).map(x=>html`<a className="intel-integration" href=${x.href}><span className=${'dot '+(x.ok?'ok':'warn')}></span><span><b>${x.name}</b><small>${x.state}</small></span><${Chip} s=${x.ok?'ok':'amber'}>${x.ok?'Ready':'Attention'}<//></a>`)}</div></section>`;
}
function IntelAnalytics({ d }) {
  const st=d.candidateStages||{}, src=d.candidateSources||{}, req=d.requirements||{}, people=d.people||{}, mail=d.mail||{};
  const candTotal=Object.values(st).reduce((a,b)=>a+Number(b||0),0), reqTotal=Object.values(req).reduce((a,b)=>a+Number(b||0),0), mailTotal=Number(mail.sent30||0)+Number(mail.delivered30||0)+Number(mail.bounced30||0)+Number(mail.failed30||0);
  return html`<div className="stack"><section className="panel"><div className="ph-row"><div><h2 className="ph">Executive Analytics</h2><p className="muted">Operational KPIs built from the same source records as the specialist pages.</p></div><a className="btn ghost" href="#/portal/admin/reports">Full reports</a></div><div className="intel-analytics-grid"><div><h3>Candidate funnel</h3>${Object.entries(st).sort((a,b)=>b[1]-a[1]).map(([k,v])=>html`<${IntelBar} n=${k} v=${v} total=${candTotal}/>` )}</div><div><h3>Requirements</h3>${Object.entries(req).sort((a,b)=>b[1]-a[1]).map(([k,v])=>html`<${IntelBar} n=${k} v=${v} total=${reqTotal}/>` )}</div><div><h3>Candidate sources</h3>${Object.entries(src).map(([k,v])=>html`<${IntelBar} n=${k} v=${v} total=${candTotal}/>` )}</div><div><h3>People</h3>${[['Employees',people.employees],['Consultants',people.consultants],['Students',people.students],['Administrators',people.admins]].map(([k,v])=>html`<${IntelBar} n=${k} v=${v} total=${people.active||1}/>` )}</div></div></section>
    <section className="panel"><h3 className="ph">Communication performance · last 30 days</h3><div className="intel-metrics"><div className="intel-metric"><span>Delivered</span><b>${intelNum(mail.delivered30)}</b></div><div className="intel-metric"><span>Bounced</span><b>${intelNum(mail.bounced30)}</b></div><div className="intel-metric"><span>Failed</span><b>${intelNum(mail.failed30)}</b></div><div className="intel-metric"><span>Bounce rate</span><b>${intelPct(mail.bounced30,mailTotal)}%</b></div></div></section>
  </div>`;
}
function IntelContactGrabber() {
  const toast=useToast(); const[text,setText]=useState(''); const[rows,setRows]=useState([]); const[reqs,setReqs]=useState([]); const[owners,setOwners]=useState([]); const[busy,setBusy]=useState(''); const[tag,setTag]=useState(''); const[owner,setOwner]=useState(''); const[mode,setMode]=useState('both');
  const preview=async()=>{if(!text.trim())return toast('Paste vendor/recruiter email text or signatures first.',true);setBusy('preview');try{const r=await api('vms_contact_grab',{text},{timeout:90000});setRows((r.rows||[]).map(x=>({...x,on:x.on!==false})));setReqs((r.requirements||[]).map(x=>({...x,on:x.on!==false})));setOwners(r.owners||[]);if(!r.n&&!r.requirementCount)toast('No contacts or requirements were found.',true);}catch(e){toast(errText(e),true)}setBusy('')};
  const chosen=rows.filter(x=>x.on!==false), chosenReqs=reqs.filter(x=>x.on!==false);
  const save=async()=>{if(!chosen.length&&!chosenReqs.length)return;setBusy('save');try{const r=await api('vms_contact_grab_save',{rows,requirements:reqs,tag,owner,mode,st:'open'},{timeout:120000});toast(`${r.added||0} contact${r.added===1?'':'s'} added, ${r.updated||0} updated${r.held?`, ${r.held} unsafe/suppressed held`:''}${r.requirements?`, ${r.requirements} requirement${r.requirements===1?'':'s'} added`:''}.`);setRows([]);setReqs([]);setText('')}catch(e){toast(errText(e),true)}setBusy('')};
  const campaign=()=>{const list=chosen.filter(x=>x.validation&&x.validation.st!=='bad'&&!x.suppressed).map(x=>({name:x.name||'',email:x.email}));if(!list.length)return toast('No selected sendable contacts are available for a campaign.',true);sessionStorage.setItem('se_mail_picked',JSON.stringify(list));location.hash='#/portal/admin/mail-campaigns';};
  const setRow=(i,k,v)=>setRows(a=>a.map((x,j)=>j===i?{...x,[k]:v}:x)); const setReq=(i,v)=>setReqs(a=>a.map((x,j)=>j===i?{...x,on:v}:x));
  const validTone=s=>s==='good'?'ok':s==='bad'?'red':'amber';
  return html`<div className="stack"><section className="panel stack"><div className="ph-row"><div><div className="eyebrow">Recruiting intake</div><h2 className="ph">Contact Grabber</h2><p className="muted">Paste an entire vendor or recruiter thread. StratEdge extracts every contact, classifies Vendor Recruiter / Bench Sales / Recruiter, checks duplicates and email health, and finds requirements in the same message.</p></div><a className="btn ghost" href="#/portal/admin/mail">Open Contacts</a></div><textarea rows="12" value=${text} onInput=${e=>setText(e.target.value)} placeholder=${'Paste a vendor email thread, signatures, requirement email or contact list here…'}></textarea><div className="actions"><button className="btn" disabled=${!!busy||!text.trim()} onClick=${preview}>${busy==='preview'?'Analyzing…':'Grab contacts + requirements'}</button>${rows.length||reqs.length?html`<button className="btn ghost" disabled=${!!busy||!chosen.length} onClick=${campaign}>Campaign selected</button>`:null}</div></section>
  ${rows.length?html`<section className="panel stack"><div className="ph-row"><div><h3 className="ph">Contacts found</h3><p className="muted small" style=${{margin:0}}>${chosen.length} selected · bad/suppressed addresses are held from saving and campaigns.</p></div><div className="actions"><button className="btn ghost sm" onClick=${()=>setRows(a=>a.map(x=>({...x,on:true})))}>Select all</button><button className="btn ghost sm" onClick=${()=>setRows(a=>a.map(x=>({...x,on:false})))}>Clear</button></div></div><div className="row3"><${Field} label="Save mode"><select value=${mode} onChange=${e=>setMode(e.target.value)}><option value="both">New + existing</option><option value="new">New only</option><option value="existing">Update existing only</option></select><//><${Field} label="Add tag"><input value=${tag} onInput=${e=>setTag(e.target.value)} placeholder="e.g. Healthcare vendors"/><//><${Field} label="Assign recruiter" hint="Stored as an Owner tag so it remains searchable"><select value=${owner} onChange=${e=>setOwner(e.target.value)}><option value="">No owner</option>${owners.map(x=>html`<option value=${x.id}>${x.name||x.email}</option>`)}</select><//></div><div className="tablewrap"><table><thead><tr><th></th><th>Contact</th><th>Company / title</th><th>Type</th><th>Email health</th><th>Record</th></tr></thead><tbody>${rows.map((r,i)=>html`<tr key=${r.email}><td><input type="checkbox" checked=${r.on!==false} onChange=${e=>setRow(i,'on',e.target.checked)}/></td><td><b>${r.name||'—'}</b><div className="small">${r.email}</div>${r.phone&&html`<div className="muted small">${r.phone}</div>`}</td><td>${r.company||'—'}${r.title&&html`<div className="muted small">${r.title}</div>`}</td><td><${Chip}>${r.kind||'Recruiter'}<//></td><td><${Chip} s=${validTone((r.validation||{}).st)}>${(r.validation||{}).st||'unknown'}<//>${r.suppressed&&html` <${Chip} s="red">Suppressed<//>`}<div className="muted small">${((r.validation||{}).why||[]).slice(0,2).join(' · ')}</div></td><td><${Chip} s=${r.existing?'amber':'ok'}>${r.existing?'Existing':'New'}<//></td></tr>`)}</tbody></table></div></section>`:null}
  ${reqs.length?html`<section className="panel stack"><div className="ph-row"><div><h3 className="ph">Requirements found in the same thread</h3><p className="muted small" style=${{margin:0}}>Save these with the contacts so the vendor relationship and recruiting work start together.</p></div><${Chip} s="ok">${chosenReqs.length} selected<//></div><div className="tablewrap"><table><thead><tr><th></th><th>Role</th><th>Client / vendor</th><th>Location</th><th>Warnings</th></tr></thead><tbody>${reqs.map((x,i)=>html`<tr key=${x.key||i}><td><input type="checkbox" checked=${x.on!==false} disabled=${!!x.dup||x.kind!=='req'} onChange=${e=>setReq(i,e.target.checked)}/></td><td><b>${(x.f||{}).ti||'Untitled'}</b><div className="muted small">${x.subject||''}</div></td><td>${(x.f||{}).cl||(x.f||{}).vn||(x.f||{}).co||'—'}<div className="muted small">${((x.from||{}).e)||''}</div></td><td>${(x.f||{}).loc||'—'}</td><td>${x.dup?html`<${Chip} s="amber">Duplicate<//>`:(x.warn||[]).length?html`<span className="small">${(x.warn||[]).slice(0,2).join(' · ')}</span>`:html`<${Chip} s="ok">Ready<//>`}</td></tr>`)}</tbody></table></div></section>`:null}
  ${(rows.length||reqs.length)&&html`<section className="panel"><div className="ph-row"><div><h3 className="ph">Finish intake</h3><p className="muted small" style=${{margin:0}}>Save selected contacts and requirements together. Existing contacts are enriched without creating duplicate email records.</p></div><button className="btn" disabled=${!!busy||(!chosen.length&&!chosenReqs.length)} onClick=${save}>${busy==='save'?'Saving…':`Save ${chosen.length} contact${chosen.length===1?'':'s'}${chosenReqs.length?` + ${chosenReqs.length} requirement${chosenReqs.length===1?'':'s'}`:''}`}</button></div></section>`}</div>`;
}

function IntelAiAutomation({ d }) {
  const prompts=['Summarize the highest-priority operational risks shown on this page.','Which recruiting records should my team work first today?','Explain the current data-quality risks and give me a cleanup order.','Draft a daily executive brief from the metrics on this page.'];
  return html`<div className="stack"><section className="panel"><div className="ph-row"><div><h2 className="ph">StratEdge AI Copilot 2.0</h2><p className="muted">Use the existing assistant with operational prompts. It follows the user’s permissions and never changes records from chat.</p></div><button className="btn" onClick=${intelOpenAi}><${AiMark} size=${16}/>Open StratEdge AI</button></div><div className="intel-prompts">${prompts.map(p=>html`<button className="intel-prompt" onClick=${async()=>{try{await navigator.clipboard.writeText(p)}catch(e){}intelOpenAi()}}><b>${p}</b><small>Copies the prompt and opens AI</small></button>`)}</div></section>
    <section className="panel"><h3 className="ph">Recruiting pipeline automation</h3><p className="muted">The automation layer reuses ATS stages, Sequences, Tasks, Campaigns and Approvals instead of creating a second workflow engine.</p><div className="actions"><a className="btn ghost" href="#/portal/admin/ats">ATS stages</a><a className="btn ghost" href="#/portal/admin/sequences">Sequences</a><a className="btn ghost" href="#/portal/admin/tasks">Tasks</a><a className="btn ghost" href="#/portal/admin/approvals">Approvals</a><a className="btn ghost" href="#/portal/admin/mail-campaigns">Campaigns</a></div></section>
    <section className="panel"><h3 className="ph">Notification Center</h3><p className="muted">This command center’s exception feed is the first notification layer: ${intelNum((d.alerts||[]).length)} current attention item(s). Open the Command Center for the live queue.</p></section>
  </div>`;
}
function IntelBulk() {
  const rows=[['Candidates / ATS','Select candidates, change stages, assign, email, tag or move through the pipeline.','#/portal/admin/ats'],['Email contacts','Select contacts, validate selected, tag, email or clean bad/duplicate records.','#/portal/admin/mail'],['Contact Cleanup','Preview bounced/rejected and duplicate cleanup before applying.','#/portal/admin/mail-cleanup'],['Requirements','Work requirements, match candidates and submit people.','#/portal/admin/vreqs'],['Campaigns','Create audience segments, test, send, pause or resume.','#/portal/admin/mail-campaigns'],['Import with preview','Bulk add/update records with field mapping and duplicate rules.','#/portal/admin/import']];
  return html`<section className="panel stack"><div><h2 className="ph">Bulk Action Center</h2><p className="muted">Bulk actions remain in the owning module so permissions, validation and audit rules stay intact. This center gets staff to the right bulk workflow quickly.</p></div><div className="intel-cap-grid">${rows.map(([n,d,h])=>html`<a className="intel-cap" href=${h}><span className="intel-cap-no">↗</span><span><b>${n}</b><small>${d}</small></span></a>`)}</div></section>`;
}

function IntelWorkQueue() {
  const toast=useToast();const[d,setD]=useState(null);const[busy,setBusy]=useState(false);
  const load=async()=>{setBusy(true);try{setD(await api('intel_work_queue',{}, {timeout:120000}))}catch(e){toast(errText(e),true)}setBusy(false)};useEffect(()=>{load()},[]);
  return html`<section className="panel stack"><div className="ph-row"><div><h2 className="ph">Recruiter Work Queue</h2><p className="muted">A prioritized daily queue from requirement SLA risk, stale candidate stages and communication health.</p></div><button className="btn ghost" disabled=${busy} onClick=${load}><${Icon} n="refresh" />${busy?'Refreshing…':'Refresh'}</button></div>
    ${!d?html`<${Spinner} label="Building recruiter queue…"/>`:(d.rows||[]).length?html`<div className="intel-alerts">${d.rows.map((x,i)=>html`<a className=${'intel-alert '+x.sev} href=${x.href} key=${i}><span className="intel-dot"></span><span><b>${x.title}</b><small>${x.kind} · ${x.detail}</small></span></a>`)}</div>`:html`<${Empty} title="No priority work found">Nothing in the tracked areas needs attention right now.<//>`}
  </section>`;
}
function IntelReadiness() {
  const toast=useToast();const[cq,setCq]=useState('');const[rq,setRq]=useState('');const[cs,setCs]=useState([]);const[rs,setRs]=useState([]);const[cid,setCid]=useState('');const[rid,setRid]=useState('');const[d,setD]=useState(null);const[busy,setBusy]=useState('');
  const search=async(kind)=>{const q=(kind==='c'?cq:rq).trim();if(q.length<2)return;setBusy(kind);try{const x=await api('intel_search',{q});const rows=(x.rows||[]).filter(z=>z.type===(kind==='c'?'Candidate':'Requirement'));kind==='c'?setCs(rows):setRs(rows)}catch(e){toast(errText(e),true)}setBusy('')};
  const run=async()=>{if(!cid||!rid)return toast('Choose both a candidate and a requirement.',true);setBusy('run');try{setD(await api('intel_readiness',{candidate:cid,requirement:rid},{timeout:120000}))}catch(e){toast(errText(e),true)}setBusy('')};
  return html`<div className="stack"><section className="panel stack"><div><h2 className="ph">Submission Readiness Gate</h2><p className="muted">Checks candidate contact health, resume, work authorization, location, skills, requirement fit and duplicate submission history before sending.</p></div>
    <div className="row2"><div><div className="lbl">Candidate</div><div className="intel-search"><input value=${cq} onInput=${e=>setCq(e.target.value)} placeholder="Name or email"/><button className="btn ghost" disabled=${busy==='c'} onClick=${()=>search('c')}>Find</button></div>${cs.length?html`<div className="intel-picks">${cs.slice(0,10).map(x=>html`<button className=${'btn ghost sm '+(cid===x.id?'on':'')} onClick=${()=>setCid(x.id)}>${x.name}<small>${x.sub}</small></button>`)}</div>`:null}</div>
      <div><div className="lbl">Requirement</div><div className="intel-search"><input value=${rq} onInput=${e=>setRq(e.target.value)} placeholder="Title, client or skill"/><button className="btn ghost" disabled=${busy==='r'} onClick=${()=>search('r')}>Find</button></div>${rs.length?html`<div className="intel-picks">${rs.slice(0,10).map(x=>html`<button className=${'btn ghost sm '+(rid===x.id?'on':'')} onClick=${()=>setRid(x.id)}>${x.name}<small>${x.sub}</small></button>`)}</div>`:null}</div></div>
    <div className="actions"><button className="btn" disabled=${busy==='run'||!cid||!rid} onClick=${run}>${busy==='run'?'Checking…':'Check readiness'}</button></div></section>
    ${d&&html`<section className="panel"><div className="ph-row"><div><h3 className="ph">${d.candidate.name} → ${d.requirement.title}</h3><p className="muted">${d.requirement.client||'Client not set'} · requirement match ${d.match}%</p></div><${Chip} s=${d.status==='ready'?'ok':d.status==='blocked'?'red':'amber'}>${d.status==='ready'?'Ready':d.status==='blocked'?'Blocked':'Needs attention'} · ${d.readiness}%<//></div><div className="intel-quality-grid">${(d.checks||[]).map(x=>html`<div className=${'intel-quality '+(x.ok?'ok':'warn')}><span><b>${x.n}</b><small>${x.detail}</small></span><b>${x.ok?'✓':'!'}</b></div>`)}</div>${(d.prior||[]).length?html`<div className="notice warn" style=${{marginTop:12}}><b>Submission conflict:</b> ${(d.prior||[]).length} earlier submission${d.prior.length===1?'':'s'} found for this requirement.</div>`:null}<div className="actions" style=${{marginTop:12}}><a className="btn ghost" href=${d.href}>Open Requirements desk</a></div></section>`}
  </div>`;
}
function IntelClient360() {
  const toast=useToast();const[q,setQ]=useState('');const[rows,setRows]=useState([]);const[id,setId]=useState('');const[d,setD]=useState(null);const[busy,setBusy]=useState(false);
  const find=async e=>{e&&e.preventDefault();if(q.trim().length<2)return;setBusy(true);try{const r=await api('intel_client_search',{q:q.trim()});setRows(r.rows||[])}catch(e){toast(errText(e),true)}setBusy(false)};
  const load=async x=>{setBusy(true);try{setD(await api('intel_client',{id:x}));setId(x)}catch(e){toast(errText(e),true)}setBusy(false)};
  return html`<div className="stack"><section className="panel stack"><div><h2 className="ph">Client 360</h2><p className="muted">Contacts, requirements, submissions, CRM deals and activity for one client/vendor account.</p></div><form className="intel-search" onSubmit=${find}><input value=${q} onInput=${e=>setQ(e.target.value)} placeholder="Client, vendor, website or location"/><button className="btn ghost" disabled=${busy}>Find client</button></form>${rows.length?html`<div className="intel-picks">${rows.map(x=>html`<button className="btn ghost sm" onClick=${()=>load(x.id)}>${x.name}<small>${x.sub}</small></button>`)}</div>`:null}</section>
    ${d&&html`<section className="panel"><div className="ph-row"><div><h3 className="ph">${d.account.n||'Client'}</h3><p className="muted">${d.account.ty||'Account'} · ${d.account.loc||'Location not set'} · ${d.account.web||''}</p></div><a className="btn ghost sm" href="#/portal/admin/crm">Open CRM</a></div><div className="intel-metrics">${[['Contacts',d.stats.contacts],['Requirements',d.stats.requirements],['Submissions',d.stats.submissions],['Deals',d.stats.deals]].map(([n,v])=>html`<div className="intel-metric"><span>${n}</span><b>${intelNum(v)}</b></div>`)}</div></section>`}
    ${d&&html`<section className="panel"><h3 className="ph">Requirements & submissions</h3><div className="tablewrap"><table><thead><tr><th>Requirement</th><th>Status</th><th>Location</th><th>Rate</th></tr></thead><tbody>${(d.requirements||[]).slice(0,40).map(x=>html`<tr><td>${x.title}</td><td>${x.status||'—'}</td><td>${x.location||'—'}</td><td>${x.rate||'—'}</td></tr>`)}</tbody></table></div>${!(d.requirements||[]).length&&html`<p className="muted">No linked requirements were found.</p>`}</section>`}
    ${d&&html`<section className="panel"><h3 className="ph">Contacts</h3>${(d.contacts||[]).length?html`<div className="intel-results">${d.contacts.slice(0,40).map(x=>html`<div className="intel-result"><span className="chip">Contact</span><span><b>${x.n||x.e||'Contact'}</b><small>${x.e||''} · ${x.ti||x.rel||''}</small></span></div>`)}</div>`:html`<p className="muted">No CRM contacts linked to this account.</p>`}</section>`}
  </div>`;
}
function IntelSla() {
  const toast=useToast();const[d,setD]=useState(null);const[busy,setBusy]=useState(false);const load=async()=>{setBusy(true);try{setD(await api('intel_sla'))}catch(e){toast(errText(e),true)}setBusy(false)};useEffect(()=>{load()},[]);
  return html`<section className="panel stack"><div className="ph-row"><div><h2 className="ph">Requirement SLA Center</h2><p className="muted">Open requirement age and time to first submission. High/urgent requirements use a tighter first-submission target.</p></div><button className="btn ghost" disabled=${busy} onClick=${load}><${Icon} n="refresh" />Refresh</button></div>${d&&html`<div className="intel-metrics"><div className="intel-metric"><span>Open</span><b>${d.open}</b></div><div className="intel-metric"><span>Breached</span><b>${d.breach}</b></div><div className="intel-metric"><span>At risk</span><b>${d.risk}</b></div></div>`}${d&&html`<div className="tablewrap"><table><thead><tr><th>Requirement</th><th>Client</th><th>Age</th><th>First submission</th><th>Priority</th><th>Risk</th></tr></thead><tbody>${(d.rows||[]).map(x=>html`<tr><td><a href=${x.href}>${x.title}</a></td><td>${x.client||'—'}</td><td>${x.ageDays}d</td><td>${x.firstSubmissionHours==null?'Not yet':x.firstSubmissionHours+'h'}</td><td>${x.priority}</td><td><${Chip} s=${x.risk==='breach'?'red':x.risk==='risk'?'amber':'ok'}>${x.risk}<//></td></tr>`)}</tbody></table></div>`}</section>`;
}

function IntelMargin() {
  const[f,setF]=useState({bill:85,pay:60,hours:40,weeks:4.33,burden:12,benefits:0,vendor:0});
  const n=k=>Math.max(0,Number(f[k]||0));const hours=n('hours')*n('weeks');const revenue=n('bill')*hours;const wages=n('pay')*hours;const burden=wages*n('burden')/100;const vendor=revenue*n('vendor')/100;const benefits=n('benefits');const cost=wages+burden+vendor+benefits;const margin=revenue-cost;const pct=revenue>0?margin*100/revenue:0;
  const up=k=>e=>setF({...f,[k]:e.target.value});
  return html`<div className="stack"><section className="panel stack"><div><h2 className="ph">Smart Rate & Margin Calculator</h2><p className="muted">Estimate gross monthly margin before a submission or placement. This is an operational estimate; Accounting remains the source of truth for payroll/taxes.</p></div><div className="row3"><${Field} label="Bill rate / hour"><input type="number" min="0" step="0.01" value=${f.bill} onInput=${up('bill')}/><//><${Field} label="Pay rate / hour"><input type="number" min="0" step="0.01" value=${f.pay} onInput=${up('pay')}/><//><${Field} label="Hours / week"><input type="number" min="0" step="0.25" value=${f.hours} onInput=${up('hours')}/><//><${Field} label="Weeks / month"><input type="number" min="0" step="0.01" value=${f.weeks} onInput=${up('weeks')}/><//><${Field} label="Employer burden %"><input type="number" min="0" step="0.1" value=${f.burden} onInput=${up('burden')}/><//><${Field} label="Vendor fee % of revenue"><input type="number" min="0" step="0.1" value=${f.vendor} onInput=${up('vendor')}/><//><${Field} label="Monthly benefits / other cost"><input type="number" min="0" step="1" value=${f.benefits} onInput=${up('benefits')}/><//></div></section><section className="panel"><div className="intel-metrics"><div className="intel-metric"><span>Monthly revenue</span><b>$${revenue.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><div className="intel-metric"><span>Estimated cost</span><b>$${cost.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><div className="intel-metric"><span>Gross margin</span><b>$${margin.toLocaleString(undefined,{maximumFractionDigits:0})}</b></div><div className="intel-metric"><span>Gross margin %</span><b>${pct.toFixed(1)}%</b></div></div><div className="notice info" style=${{marginTop:12}}>Cost estimate includes pay, ${n('burden').toFixed(1)}% employer burden, vendor fee and entered monthly benefits/other cost. It does not replace payroll, tax or accounting calculations.</div></section></div>`;
}
function IntelDeliverability() {
  const toast=useToast();const[d,setD]=useState(null);const[busy,setBusy]=useState(false);const load=async refresh=>{setBusy(true);try{setD(await api('intel_deliverability',{refresh:!!refresh},{timeout:120000}))}catch(e){toast(errText(e),true)}setBusy(false)};useEffect(()=>{load(false)},[]);
  const c=d&&d.check;return html`<div className="stack"><section className="panel"><div className="ph-row"><div><h2 className="ph">Deliverability Control Center</h2><p className="muted">Sender authentication, reputation, warm-up, bounce/complaint health and recent failures.</p></div><div className="actions"><button className="btn ghost" disabled=${busy} onClick=${()=>load(true)}><${Icon} n="refresh" />${busy?'Checking…':'Run live checks'}</button><a className="btn" href="#/portal/admin/mail">Email settings</a></div></div>${c&&html`<div className="intel-metrics"><div className="intel-metric"><span>Health score</span><b>${c.score}%</b></div><div className="intel-metric"><span>Fix</span><b>${c.sum&&c.sum.fail||0}</b></div><div className="intel-metric"><span>Improve</span><b>${c.sum&&c.sum.warn||0}</b></div><div className="intel-metric"><span>OK</span><b>${c.sum&&c.sum.ok||0}</b></div></div>`}</section>${c&&html`<section className="panel"><div className="intel-results">${(c.checks||[]).map(x=>html`<div className="intel-result"><span className=${'chip '+(x.st==='fail'?'red':x.st==='warn'?'amber':'ok')}>${x.st==='fail'?'Fix':x.st==='warn'?'Improve':'OK'}</span><span><b>${x.t}</b><small>${x.d||x.fix||''}</small></span></div>`)}</div></section>`}</div>`;
}
function IntelReplay() {
  const toast=useToast();const[d,setD]=useState([]);const[busy,setBusy]=useState('');const load=async()=>{try{const r=await api('intel_events');setD(r.rows||[])}catch(e){toast(errText(e),true)}};useEffect(()=>{load()},[]);
  const replay=async k=>{if(!confirm('Replay this supported integration action now?'))return;setBusy(k);try{await api('intel_replay',{kind:k},{timeout:360000});toast('Integration action replayed.');await load()}catch(e){toast(errText(e),true)}setBusy('')};
  return html`<section className="panel stack"><div><h2 className="ph">Webhook & Integration Replay Center</h2><p className="muted">Recent integration events from the tamper-evident audit log. Supported actions can be replayed by an administrator after reauthentication.</p></div>${d.length?html`<div className="tablewrap"><table><thead><tr><th>When</th><th>Action</th><th>Target</th><th>By</th><th></th></tr></thead><tbody>${d.map(x=>html`<tr><td>${x.at?fmtTs(x.at):'—'}</td><td>${x.act}</td><td>${x.target||'—'}</td><td>${x.who||'System'}</td><td>${x.replay?html`<button className="btn ghost sm" disabled=${!!busy} onClick=${()=>replay(x.replay)}>${busy===x.replay?'Running…':'Replay'}</button>`:'—'}</td></tr>`)}</tbody></table></div>`:html`<${Empty} title="No recent integration events">Events appear here after connected services run.<//>`}</section>`;
}
function IntelForecast() {
  const toast=useToast();const[d,setD]=useState(null);useEffect(()=>{api('intel_forecast').then(setD).catch(e=>toast(errText(e),true))},[]);return html`<section className="panel stack"><div><h2 className="ph">Executive Forecasting</h2><p className="muted">Directional 90-day placement forecast from current recruiting stages. It is intentionally labeled as an estimate, not an actual result.</p></div>${d?html`<div className="intel-metrics"><div className="intel-metric"><span>Expected placements · 90d</span><b>${d.expectedPlacements90}</b></div><div className="intel-metric"><span>Open requirements</span><b>${d.openRequirements}</b></div></div><div className="notice info">${d.note}</div>`:html`<${Spinner} />`}</section>`;
}
function IntelActions() {
  const toast=useToast();const[rows,setRows]=useState([]);const[f,setF]=useState({type:'candidate_tag',target:'',text:''});const[busy,setBusy]=useState('');const load=async()=>{try{const r=await api('intel_actions');setRows(r.rows||[])}catch(e){toast(errText(e),true)}};useEffect(()=>{load()},[]);
  const propose=async()=>{setBusy('new');try{await api('intel_action_propose',f);setF({...f,target:'',text:''});toast('Action proposed for approval.');await load()}catch(e){toast(errText(e),true)}setBusy('')};
  const decide=async(id,decision)=>{setBusy(id+decision);try{await api('intel_action_decide',{id,decision});toast(decision==='approve'?'Action approved and applied.':'Action rejected.');await load()}catch(e){toast(errText(e),true)}setBusy('')};
  return html`<div className="stack"><section className="panel stack"><div><h2 className="ph">AI Action Agent with Approval</h2><p className="muted">Prepare an operational action, review it, then approve or reject it. Record changes are never applied at proposal time.</p></div><div className="row3"><${Field} label="Action"><select value=${f.type} onChange=${e=>setF({...f,type:e.target.value})}><option value="candidate_tag">Add candidate tag</option><option value="candidate_note">Add candidate note</option><option value="requirement_note">Add requirement note</option></select><//><${Field} label="Candidate / requirement ID"><input value=${f.target} onInput=${e=>setF({...f,target:e.target.value})} placeholder="Record ID"/><//><${Field} label="Proposed value"><input value=${f.text} onInput=${e=>setF({...f,text:e.target.value})} placeholder="Tag or note"/><//></div><div className="actions"><button className="btn" disabled=${busy==='new'||!f.target.trim()||!f.text.trim()} onClick=${propose}>${busy==='new'?'Proposing…':'Propose action'}</button></div></section>
    <section className="panel"><h3 className="ph">Approval queue</h3>${rows.length?html`<div className="tablewrap"><table><thead><tr><th>Action</th><th>Target</th><th>Value</th><th>Status</th><th>Proposed by</th><th></th></tr></thead><tbody>${rows.map(x=>html`<tr><td>${x.type}</td><td>${x.target}</td><td>${x.text}</td><td><${Chip} s=${x.st==='approved'?'ok':x.st==='rejected'?'red':'amber'}>${x.st}<//></td><td>${x.byn||'—'}</td><td>${x.st==='pending'?html`<div className="actions"><button className="btn sm" disabled=${!!busy} onClick=${()=>decide(x.id,'approve')}>Approve</button><button className="btn ghost sm" disabled=${!!busy} onClick=${()=>decide(x.id,'reject')}>Reject</button></div>`:(x.result||'—')}</td></tr>`)}</tbody></table></div>`:html`<${Empty} title="No proposed actions">Proposed actions will wait here for approval.<//>`}</section></div>`;
}

function IntelligencePage({ q }) {
  const toast=useToast(); const tab0=INTEL_TABS.some(x=>x[0]===q.tab)?q.tab:'overview'; const[tab,setTab]=useState(tab0);const[d,setD]=useState(null);const[busy,setBusy]=useState(false);
  const load=async()=>{setBusy(true);try{setD(await api('intel_summary',{}, {timeout:120000}))}catch(e){toast(errText(e),true)}setBusy(false)};
  useEffect(()=>{load()},[]); useEffect(()=>{if(q.tab&&q.tab!==tab&&INTEL_TABS.some(x=>x[0]===q.tab))setTab(q.tab)},[q.tab]);
  if(!d)return html`<div className="panel"><${Spinner} label=${busy?'Building the live operating view…':'Loading…'}/></div>`;
  return html`<div className="intel-page"><div className="panel intel-tabs">${INTEL_TABS.map(([k,n])=>html`<button className=${tab===k?'on':''} onClick=${()=>setTab(k)}>${n}</button>`)}</div>
    ${tab==='overview'&&html`<${IntelOverview} d=${d} reload=${load}/>`}
    ${tab==='work'&&html`<${IntelWorkQueue}/>`}
    ${tab==='readiness'&&html`<${IntelReadiness}/>`}
    ${tab==='client'&&html`<${IntelClient360}/>`}
    ${tab==='sla'&&html`<${IntelSla}/>`}
    ${tab==='margin'&&html`<${IntelMargin}/>`}
    ${tab==='search'&&html`<${IntelSearch}/>`}
    ${tab==='candidate'&&html`<${IntelCandidate} initial=${q.candidate||''}/>`}
    ${tab==='quality'&&html`<${IntelQuality} d=${d}/>`}
    ${tab==='deliverability'&&html`<${IntelDeliverability}/>`}
    ${tab==='integrations'&&html`<${IntelIntegrations} d=${d}/>`}
    ${tab==='replay'&&html`<${IntelReplay}/>`}
    ${tab==='analytics'&&html`<${IntelAnalytics} d=${d}/>`}
    ${tab==='forecast'&&html`<${IntelForecast}/>`}
    ${tab==='grabber'&&html`<${IntelContactGrabber}/>`}
    ${tab==='actions'&&html`<${IntelActions}/>`}
    ${tab==='ai'&&html`<${IntelAiAutomation} d=${d}/>`}
    ${tab==='bulk'&&html`<${IntelBulk}/>`}
  </div>`;
}
