'use strict';importScripts('core.js');const C=ApplyCore;const DAY=()=>new Date().toLocaleDateString('en-CA');const matchPattern=url=>{const u=new URL(url);return u.protocol+'//'+u.hostname+'/*';};let active=false;
chrome.storage.local.setAccessLevel?.({accessLevel:'TRUSTED_CONTEXTS'});
async function read(){const v=await chrome.storage.local.get(['dashboard','engine','updates','ledger']);return {dashboard:v.dashboard,engine:v.engine||{running:false,jobs:[]},updates:v.updates||{},ledger:v.ledger||{day:DAY(),count:0,attempted:[]}};}
/* v83: ACK forgets the reports the portal saved, from the direct path and from the page bridge alike; a report that changed after the portal read it (updatedAt differs) is kept. */
async function ack(ids,at){const {updates}=await read();for(const id of Array.isArray(ids)?ids.slice(0,500):[])if(typeof id==='string'&&updates[id]&&(!at||typeof at!=='object'||!at[id]||updates[id].updatedAt===at[id]))delete updates[id];await chrome.storage.local.set({updates});return {left:Object.keys(updates).length};}
async function notify(message){const {dashboard}=await read();if(!dashboard)return;const tabs=await chrome.tabs.query({});for(const tab of tabs){try{if(tab.url&&new URL(tab.url).origin===dashboard.origin)await chrome.tabs.sendMessage(tab.id,message);}catch{}}}
async function updateJob(job,status,note){const {updates}=await read();const patch={id:job.id,status,note,updatedAt:new Date().toISOString()};updates[job.id]=patch;await chrome.storage.local.set({updates});await notify({action:'JOB_UPDATE',payload:patch});}
async function stop(){const {engine}=await read();engine.running=false;engine.jobs=[];if(engine.current&&!engine.current.attempted){await updateJob(engine.current.job,'review','Bot paused. Continue manually or requeue this job.');engine.current=null;}await chrome.storage.local.set({engine});await notify({action:'BOT_STATUS',payload:{running:false}});}
async function dashboardSender(sender){const {dashboard}=await read();if(!dashboard||!sender.tab?.url)return false;try{return new URL(sender.tab.url).origin===dashboard.origin;}catch{return false;}}
async function configure(url){url=C.safeUrl(url);const u=new URL(url);if(u.hash)u.hash='';await chrome.storage.local.set({dashboard:{url:u.href,origin:u.origin}});try{await chrome.scripting.unregisterContentScripts({ids:['applypilot-dashboard']});}catch{}await chrome.scripting.registerContentScripts([{id:'applypilot-dashboard',matches:[matchPattern(u.href)],js:['bridge.js'],runAt:'document_idle',persistAcrossSessions:true,allFrames:true}]);}
async function run(payload){if(!payload||!Array.isArray(payload.jobs)||!payload.jobs.length||payload.jobs.length>100)throw Error('Add between 1 and 100 jobs to run.');const {engine:old}=await read();if(old.running||old.current?.attempted)throw Error('A job is already running or awaiting confirmation.');const cleaned=C.validateState({version:1,profile:payload.profile,settings:payload.settings,jobs:payload.jobs});let ledger=(await read()).ledger;if(ledger.day!==DAY())ledger={...ledger,day:DAY(),count:0};for(const j of cleaned.jobs){if(['submitted','uncertain'].includes(j.status))throw Error('A submitted or uncertain application cannot be rerun automatically.');if(C.portalFor(j.url))throw Error('Job boards use a manual handoff. Run an employer application instead.');const gate=C.automationGate(j,cleaned.profile,cleaned.settings,ledger.count);if(gate)throw Error(gate);if(!await chrome.permissions.contains({origins:[matchPattern(j.url)]})){await chrome.tabs.create({url:chrome.runtime.getURL('grant.html?u='+encodeURIComponent(j.url)),active:true});throw Error(`Allow the companion on ${new URL(j.url).hostname} in the tab that just opened (grant access once per site), then press Run again.`);}}
  const resume=payload.resume;if(resume&&(typeof resume.data!=='string'||!/^data:[^;]*;base64,/.test(resume.data)||resume.data.length>7.1*1024*1024||! /\.(pdf|docx)$/i.test(resume.name)))throw Error('The résumé attachment is invalid or too large.');await chrome.storage.local.set({engine:{running:true,jobs:cleaned.jobs,profile:cleaned.profile,resume:resume||null,settings:cleaned.settings,current:null},ledger});await notify({action:'BOT_STATUS',payload:{running:true}});await next();return {started:true};}
async function next(){let {engine}=await read();if(!engine.running||engine.current)return;if(!engine.jobs.length){engine.running=false;await chrome.storage.local.set({engine});await notify({action:'BOT_STATUS',payload:{running:false}});return;}const job=engine.jobs.shift();engine.current={job,tabId:null,stage:'loading',attempted:false,deadline:Date.now()+60000};await chrome.storage.local.set({engine});await chrome.alarms.create('applypilot-watchdog',{when:Date.now()+65000});try{const tab=await chrome.tabs.create({url:job.url,active:true});const latest=(await read()).engine;if(!latest.running||latest.current?.job.id!==job.id)return;latest.current.tabId=tab.id;await chrome.storage.local.set({engine:latest});const check=await chrome.tabs.get(tab.id);if(check.status==='complete')process(tab.id);}catch(err){await finish(job,'error','Could not open the application: '+err.message);}}
async function finish(job,status,note){const first=await read();if(first.engine.current?.job.id!==job.id)return;await updateJob(job,status,note);const {engine}=await read();if(engine.current?.job.id!==job.id)return;engine.current=null;await chrome.storage.local.set({engine});await chrome.alarms.clear('applypilot-watchdog');if(engine.running)await next();}
async function inject(tabId){await chrome.scripting.executeScript({target:{tabId},files:['core.js','form.js']});}
async function process(tabId){if(active)return;active=true;let job;try{let {engine,ledger}=await read();const cur=engine.current;if(!engine.running||!cur||cur.tabId!==tabId||cur.stage!=='loading')return;job=cur.job;cur.stage='processing';await chrome.storage.local.set({engine});const tab=await chrome.tabs.get(tabId);if(C.portalFor(tab.url)||new URL(tab.url).origin!==new URL(job.url).origin){await finish(job,'review','The application redirected to a different site. Save the new application link and grant that site access.');return;}await inject(tabId);const results=await chrome.scripting.executeScript({target:{tabId},func:(profile,resume)=>globalThis.ApplyBot.fill(profile,resume),args:[engine.profile,engine.resume]});const plan=results[0]?.result;if(!plan||plan.error){await finish(job,'review',plan?.error||'The form could not be read. Continue manually.');return;}if(engine.settings.mode==='review'){await finish(job,'review',`${plan.filled} field(s) filled. Review the open form and submit manually.${plan.missing?.length?' Needs attention: '+plan.missing.join('; '):''}`);return;}if(plan.missing?.length){await finish(job,'review',`${plan.filled} field(s) filled. Needs attention: ${plan.missing.join('; ')}`);return;}const latest=await read();engine=latest.engine;ledger=latest.ledger;if(!engine.running||engine.current?.job.id!==job.id)return;if(ledger.day!==DAY())ledger={...ledger,day:DAY(),count:0};const gate=C.automationGate(job,engine.profile,engine.settings,ledger.count);if(gate){await finish(job,'review',gate);return;}const canonical=C.canonicalUrl(job.url);if(ledger.attempted.includes(canonical)){await finish(job,'uncertain','A previous submission attempt exists for this URL. Check the employer website before taking any further action.');return;}ledger.count++;ledger.attempted.push(canonical);engine.current.stage='confirming';engine.current.attempted=true;engine.current.deadline=Date.now()+20000;await chrome.storage.local.set({engine,ledger});await updateJob(job,'uncertain','Submission is in progress. Awaiting a visible confirmation; do not resubmit.');const commit=await chrome.scripting.executeScript({target:{tabId},func:p=>globalThis.ApplyBot.commit(p),args:[plan]});if(commit[0]?.result?.clicked===false){await finish(job,'review',commit[0].result.error||'Submission did not proceed. Continue manually.');return;}await checkConfirmation(tabId,job,plan);}catch(err){if(job){const {engine}=await read();await finish(job,engine.current?.attempted?'uncertain':'error',engine.current?.attempted?'A submission was attempted, but no confirmation was verified. Check the employer website; do not resubmit automatically.':'The browser could not access this form. Check site permission and continue manually.');}}finally{active=false;const {engine}=await read();if(engine.running&&engine.current?.stage==='loading'&&engine.current.tabId){const tab=await chrome.tabs.get(engine.current.tabId).catch(()=>null);if(tab?.status==='complete')process(tab.id);}}}
async function checkConfirmation(tabId,job,plan){for(const wait of [500,1200,2200,4000,6000]){await new Promise(resolve=>setTimeout(resolve,wait));try{const tab=await chrome.tabs.get(tabId);if(tab.status!=='complete')continue;if(new URL(tab.url).origin!==new URL(job.url).origin)continue;await inject(tabId);const results=await chrome.scripting.executeScript({target:{tabId},func:()=>globalThis.ApplyBot.confirmation()});if(results[0]?.result?.confirmed&&(!plan.confirmationBefore||results[0].result.url!==plan.url)){await finish(job,'submitted','A visible application confirmation was verified.');return;}}catch{}}await finish(job,'uncertain','No clear submission confirmation was found. Check the open page or confirmation email before taking any further action.');}
chrome.tabs.onUpdated.addListener((tabId,change)=>{if(change.status==='complete')process(tabId);});
chrome.tabs.onRemoved.addListener(async tabId=>{const {engine}=await read();if(engine.current?.tabId===tabId)await finish(engine.current.job,engine.current.attempted?'uncertain':'review',engine.current.attempted?'The tab closed after a submission attempt. Verify the outcome manually.':'The application tab was closed. Requeue it if needed.');});
chrome.alarms.onAlarm.addListener(async alarm=>{if(alarm.name!=='applypilot-watchdog')return;const {engine}=await read();if(engine.current&&Date.now()>engine.current.deadline)await finish(engine.current.job,engine.current.attempted?'uncertain':'error',engine.current.attempted?'No confirmation was verified before the browser timed out. Check the result manually.':'The application did not finish loading. Check the page manually.');});
chrome.runtime.onStartup.addListener(async()=>{const {engine}=await read();if(engine.current)await updateJob(engine.current.job,engine.current.attempted?'uncertain':'review','The browser restarted. Check this application manually before continuing.');engine.running=false;engine.current=null;engine.jobs=[];await chrome.storage.local.set({engine});});
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{(async()=>{const ownPage=sender.id===chrome.runtime.id&&sender.url?.startsWith(chrome.runtime.getURL(''));if(message.action==='CONFIGURE_DASHBOARD'&&ownPage){await configure(message.url);return {result:{connected:true}};}if(message.action==='POPUP_FILL'&&ownPage)return {result:await quickFill(message.tabId)};if(message.action==='POPUP_STOP'&&ownPage){await stop();return {result:{stopped:true}};}if(!await dashboardSender(sender))throw Error('This dashboard is not connected to the companion.');if(message.action==='DASHBOARD_PING'){const {engine,updates}=await read();return {result:{version:chrome.runtime.getManifest?.().version||'1.1.0',running:engine.running,updates:Object.values(updates)}};}if(message.action==='DASHBOARD_STOP'){await stop();return {result:{stopped:true}};}if(message.action==='DASHBOARD_RUN')return {result:await run(message.payload)};if(message.action==='DASHBOARD_SYNC')return {result:await sync(message.payload,sender.tab?.url||'')};if(message.action==='DASHBOARD_ACK')return {result:await ack(message.payload?.ids,message.payload?.at)};throw Error('Unknown request.');})().then(sendResponse).catch(err=>sendResponse({error:err.message}));return true;});

/* v35: the StratEdge portal (the addresses in manifest.json externally_connectable) talks to the companion directly,
   so nobody has to enter a dashboard address. PING returns the bot state and the job updates not yet saved by the
   portal; ACK forgets the ones it saved; RUN and STOP work as from a connected dashboard.
   v83: only the StratEdge portal itself over HTTPS (the main host, www and a workspace's <name>. subdomain, never the
   hosting control-panel/mail subdomains) may use this path; localhost and any other address connect through the popup's
   "Using the portal at another address?" (the page bridge, pinned to that one origin). */
const portalSender=s=>{try{const u=new URL(s?.origin||s?.url||'');const h=u.hostname;return u.protocol==='https:'&&!u.port&&(h==='stratedgeitconsulting.com'||(/^[a-z0-9-]{1,30}\.stratedgeitconsulting\.com$/.test(h)&&!/^(mail|webmail|cpanel|whm|webdisk|cpcalendars|cpcontacts|autodiscover|autoconfig|ftp)\./.test(h)));}catch{return false;}};
chrome.runtime.onMessageExternal?.addListener((message,sender,sendResponse)=>{(async()=>{const action=message?.action;if(!portalSender(sender))throw Error('Unknown sender.');if(action==='PING'){const {engine,updates}=await read();return {result:{version:chrome.runtime.getManifest?.().version||'1.1.0',running:engine.running,updates:Object.values(updates)}};}if(action==='ACK')return {result:await ack(message.ids,message.at)};if(action==='STOP'){await stop();return {result:{stopped:true}};}if(action==='RUN')return {result:await run(message.payload)};if(action==='SYNC')return {result:await sync(message.payload,sender.url||'')};throw Error('Unknown request.');})().then(sendResponse).catch(err=>sendResponse({error:err.message}));return true;});

/* v35: the portal keeps a copy of the person's application profile and résumé here (this browser only), so the popup's
   "Fill this application" button works on any employer form in one click, without running a queue. */
async function sync(p,pageUrl){p=p||{};const st=C.validateState({version:1,profile:p.profile||{},jobs:[],settings:{}});const res=p.resume;if(res&&(typeof res.data!=='string'||!/^data:[^;]*;base64,/.test(res.data)||res.data.length>7.1*1024*1024||!/\.(pdf|docx)$/i.test(String(res.name||''))))throw Error('The résumé is invalid or too large.');let portal='';try{const u=new URL(pageUrl);if(['https:','http:'].includes(u.protocol))portal=u.origin+u.pathname+'#/portal/appbot';}catch{}await chrome.storage.local.set({synced:{profile:st.profile,resume:res?{name:String(res.name).slice(0,180),data:res.data}:null,name:String(p.name||st.profile.fullName||'').slice(0,120),portal,at:Date.now()}});return {synced:true};}
async function quickFill(tabId){const {synced}=await chrome.storage.local.get(['synced']);if(!synced?.profile)throw Error('Open Application bot in your StratEdge portal once: your profile and résumé are then ready here.');const tab=await chrome.tabs.get(tabId);if(!tab||!/^https?:/.test(tab.url||''))throw Error('Open a job application page first.');if(C.portalFor(tab.url))throw Error('Job boards are a manual handoff: fill their forms yourself.');if(!await chrome.permissions.contains({origins:[matchPattern(tab.url)]}))throw Error('Allow the companion on this site first.');await inject(tabId);const r=await chrome.scripting.executeScript({target:{tabId},func:(p,res)=>globalThis.ApplyBot.fill(p,res),args:[synced.profile,synced.resume]});const plan=r[0]?.result;if(!plan)throw Error('The form could not be read.');if(plan.error)throw Error(plan.error);return {filled:plan.filled,missing:plan.missing||[]};}
