(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.ApplyCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const VERSION=1;
  const portals=[
    {id:'dice',name:'Dice',letter:'D',color:'#dd2436',host:'dice.com',url:'https://www.dice.com',method:'Manual handoff',description:'Tech roles and contract opportunities. Save jobs here, then apply directly on Dice.',terms:'https://www.dice.com/about/terms-and-conditions'},
    {id:'linkedin',name:'LinkedIn',letter:'in',color:'#0a66c2',host:'linkedin.com',url:'https://www.linkedin.com/jobs/',method:'Manual handoff',description:'Professional networking and employer listings. Complete applications directly on LinkedIn.',terms:'https://www.linkedin.com/legal/user-agreement'},
    {id:'indeed',name:'Indeed',letter:'i',color:'#194bd6',host:'indeed.com',url:'https://www.indeed.com',method:'Manual / native tools',description:'Use direct applications or Indeed’s own Apply For Me feature if it is offered in your account.',terms:'https://www.indeed.com/legal'},
    {id:'ziprecruiter',name:'ZipRecruiter',letter:'Z',color:'#27815e',host:'ziprecruiter.com',url:'https://www.ziprecruiter.com',method:'Manual handoff',description:'Search a broad set of employers. Automated access has not been enabled in this package.'},
    {id:'monster',name:'Monster',letter:'M',color:'#6746a3',host:'monster.com',url:'https://www.monster.com',method:'Manual handoff',description:'Find roles across industries and keep a record of your applications here.'},
    {id:'glassdoor',name:'Glassdoor',letter:'G',color:'#159a65',host:'glassdoor.com',url:'https://www.glassdoor.com',method:'Manual handoff',description:'Research employers and opportunities. Apply directly through the portal or employer.'}
  ];
  function normalize(v){return String(v??'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,' ').trim();}
  function isHost(host,base){return host===base||host.endsWith('.'+base);}
  function portalFor(url){let host;try{host=new URL(url).hostname.toLowerCase();}catch{return null;}return portals.find(p=>isHost(host,p.host)||(p.id==='indeed'&&/(^|\.)indeed\.(?:co\.uk|co\.in|ca|fr|de|nl|com\.au|co\.za)$/.test(host))||(p.id==='monster'&&/(^|\.)monster\.(?:co\.uk|ca|de|fr|com\.au|co\.in)$/.test(host))||(p.id==='glassdoor'&&/(^|\.)glassdoor\.(?:co\.uk|ca|de|fr|com\.au|co\.in)$/.test(host)))||null;}
  function safeUrl(value){const u=new URL(String(value).trim());if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error('Use an HTTP or HTTPS application link without embedded credentials.');if(u.protocol==='http:'&&!['localhost','127.0.0.1','terminal.local'].includes(u.hostname))throw Error('Employer application links must use HTTPS.');return u.href;}
  function canonicalUrl(value){const u=new URL(safeUrl(value));u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(trk|source|gh_src|lever-source|referral|ref)$/i.test(k))u.searchParams.delete(k);u.searchParams.sort();u.pathname=u.pathname.replace(/\/+$/,'')||'/';return u.href;}
  function keywords(value){return String(value||'').split(/[,\n]+/).map(s=>s.trim()).filter(Boolean);}
  function keywordScore(description,skills){if(!String(description||'').trim())return null;const d=normalize(description);const keys=keywords(skills);if(!keys.length)return null;return Math.round(100*keys.filter(k=>(' '+d+' ').includes(' '+normalize(k)+' ')).length/keys.length);}
  function defaultState(){return {version:VERSION,profile:{fullName:'',firstName:'',lastName:'',email:'',phone:'',city:'',state:'',country:'',linkedin:'',website:'',currentTitle:'',yearsExperience:'',targetRoles:'Senior Network Engineer, Network Security Architect, Cloud Network Engineer, SD-WAN Architect',skills:'',workAuthorization:'',sponsorship:'',relocation:'',salary:'',answers:{}},resume:null,jobs:[],settings:{mode:'review',dailyLimit:5,minScore:40,allowedHosts:[]},activity:[]};}
  function profileProgress(profile,resume){const values=[profile.fullName,profile.firstName,profile.lastName,profile.email,profile.phone,resume?.name];return Math.round(values.filter(Boolean).length/values.length*100);}
  function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;let s=String(text).replace(/^\uFEFF/,'');for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(quoted&&s[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&s[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('The CSV has an unclosed quoted field.');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(!rows.length)return [];const headers=rows.shift().map(normalize);return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]??''])));}
  function csvCell(v){const s=String(v??'');const safe=/^[\s]*[=+@-]/.test(s)?"'"+s:s;return '"'+safe.replace(/"/g,'""')+'"';}
  function exportCSV(jobs){const headers=['title','company','url','location','status','approved','description'];return [headers.join(','),...jobs.map(j=>headers.map(h=>csvCell(j[h])).join(','))].join('\r\n');}
  function makeJob(input,jobs=[]){const url=safeUrl(input.url);if(jobs.some(j=>canonicalUrl(j.url)===canonicalUrl(url)))throw Error('This job is already in your queue.');const title=String(input.title||'').trim();const company=String(input.company||'').trim();if(!title||!company)throw Error('Add a job title and company name.');const manual=!!portalFor(url);return {id:(globalThis.crypto?.randomUUID?.()||'job-'+Date.now()+'-'+Math.random().toString(16).slice(2)),url,title,company,location:String(input.location||'').trim(),description:String(input.description||''),approved:input.approved===true,status:manual?'manual':'queued',note:manual?'Apply directly on this portal, then record the outcome here.':'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};}
  function validateState(value){if(!value||value.version!==1||!value.profile||!Array.isArray(value.jobs)||value.jobs.length>2000)throw Error('This is not a valid ApplyPilot backup.');const fresh=defaultState();const keys=Object.keys(fresh.profile).filter(k=>k!=='answers');for(const k of keys)if(value.profile[k]!=null)fresh.profile[k]=String(value.profile[k]).slice(0,12000);fresh.profile.answers={};for(const [q,a] of Object.entries(value.profile.answers||{}).slice(0,100))fresh.profile.answers[String(q).slice(0,300)]=String(a).slice(0,5000);const settings=value.settings||{};fresh.settings.mode=settings.mode==='auto'?'auto':'review';fresh.settings.dailyLimit=Math.min(50,Math.max(1,Number(settings.dailyLimit)||5));fresh.settings.minScore=Math.min(100,Math.max(0,Number(settings.minScore)||0));fresh.settings.allowedHosts=Array.isArray(settings.allowedHosts)?settings.allowedHosts.filter(h=>typeof h==='string'&&/^[a-z0-9.-]+$/i.test(h)).slice(0,50):[];const statuses=['queued','manual','review','submitted','uncertain','error','skipped'];fresh.jobs=value.jobs.map(j=>({ ...makeJob(j),id:typeof j.id==='string'?j.id:'job-'+Math.random(),status:statuses.includes(j.status)?j.status:'review',approved:j.approved===true,demo:j.demo===true,note:String(j.note||'').slice(0,5000),createdAt:String(j.createdAt||new Date().toISOString()),updatedAt:String(j.updatedAt||new Date().toISOString())}));return fresh;}
  function fieldAnswer(field,profile,resume){const labels=[field.label,field.ariaLabel,field.placeholder].map(normalize).filter(Boolean);const key=normalize(field.name||field.id||'').replace(/ /g,'');for(const q of labels){for(const [question,answer] of Object.entries(profile.answers||{})){if(normalize(question)===q&&String(answer).trim())return {value:String(answer),source:'saved answer'};}}
    if(field.type==='file'){if(/resume|curriculum vitae|\bcv\b/.test(labels.join(' '))||/resume|cvupload/.test(key))return resume?{value:resume,source:'resume',file:true}:null;return null;}
    if(['checkbox','radio'].includes(field.type))return null;
    const autocompleteMap={'given-name':'firstName','family-name':'lastName','name':'fullName','email':'email','tel':'phone','address-level2':'city','address-level1':'state','country-name':'country'};
    const ak=autocompleteMap[field.autocomplete];if(ak&&profile[ak])return {value:String(profile[ak]),source:'profile'};
    const candidates=[...labels,key];const patterns=[
      ['sponsorship',/^(?:do you (?:now or in the future )?(?:require|need) (?:visa |employer )?sponsorship|will you (?:now or in the future )?(?:require|need) (?:visa |employer )?sponsorship|(?:visa |employer )?sponsorship)(?: for employment)?$/],
      ['workAuthorization',/^(?:are you (?:legally )?authorized to work in (?:the )?(?:united states|us|u s)|(?:us )?work authorization|workauthorization)$/],
      ['firstName',/^(?:first(?: name)?|given name|first ?name|firstname)$/],['lastName',/^(?:last(?: name)?|family name|surname|last ?name|lastname)$/],
      ['fullName',/^(?:full name|your name|legal name|name|fullname)$/],['email',/^(?:email|e mail|email address|your email|emailaddress)$/],['phone',/^(?:phone|telephone|mobile|phone number|mobile number|your phone number|phonenumber)$/],
      ['city',/^(?:city|your city)$/],['state',/^(?:state|province|state province)$/],['country',/^(?:country|country of residence)$/],
      ['linkedin',/^(?:linkedin|linkedin profile|linkedin url|linkedin profile url|linkedinprofile|linkedinurl)$/],['website',/^(?:website|personal website|portfolio|portfolio url|websiteurl)$/],
      ['currentTitle',/^(?:current (?:job )?title|job title|currenttitle)$/],['yearsExperience',/^(?:total years of (?:relevant )?experience|years of (?:relevant )?experience|yearsexperience)$/],
      ['salary',/^(?:expected salary|salary expectation|desired salary|salaryexpectation)$/],['relocation',/^(?:willing to relocate|are you willing to relocate|relocation)$/]
    ];
    for(const [p,pattern] of patterns)if(candidates.some(c=>pattern.test(c))&&String(profile[p]??'').trim())return {value:String(profile[p]),source:'profile'};
    return null;
  }
  function automationGate(job,profile,settings,submittedToday=0){if(portalFor(job.url))return 'This portal uses a manual handoff.';if(!job.approved)return 'Approve this job after checking the listing.';if(!profile.email||!profile.fullName)return 'Add your name and email to your profile.';if(settings.mode==='auto'){const host=new URL(job.url).hostname;if(!settings.allowedHosts.includes(host))return 'Enable this exact employer hostname in Bot settings.';if(submittedToday>=Number(settings.dailyLimit))return 'Your daily automatic submission limit has been reached.';const score=keywordScore(job.description,profile.skills);if(score===null)return 'Add the job description and your skills before automatic submission.';if(score<Number(settings.minScore))return 'Keyword coverage is below your automatic submission threshold.';}return null;}
  return {VERSION,portals,normalize,isHost,portalFor,safeUrl,canonicalUrl,keywords,keywordScore,defaultState,profileProgress,parseCSV,exportCSV,makeJob,validateState,fieldAnswer,automationGate};
});
