(()=>{'use strict';const C=globalThis.ApplyCore;
  const visible=e=>!!(e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'&&getComputedStyle(e).display!=='none');
  const compact=s=>String(s||'').replace(/\s+/g,' ').trim().replace(/\s*\*\s*$/,'');
  function descriptor(el){const fieldset=el.closest('fieldset');const groupLabel=fieldset?.querySelector('legend')?.textContent;return {type:el.type||el.tagName.toLowerCase(),label:compact((el.type==='radio'?groupLabel:null)||[...el.labels||[]].map(l=>l.textContent).join(' ')||groupLabel||''),ariaLabel:compact(el.getAttribute('aria-label')),placeholder:compact(el.placeholder),name:el.name,id:el.id,autocomplete:el.autocomplete,required:el.required||el.getAttribute('aria-required')==='true'};}
  function blockers(){if([...document.querySelectorAll('input[type=password]')].some(visible))return 'Login is required. Sign in manually, then run this job again.';if([...document.querySelectorAll('iframe')].some(e=>visible(e)&&/recaptcha|hcaptcha|turnstile|captcha/i.test(e.src+' '+e.title)))return 'Complete the CAPTCHA or security check manually.';if(/verify you are human|checking your browser|unusual traffic|access denied|are you a robot/i.test(document.body?.innerText||''))return 'This page requires a security check. Continue manually.';return null;}
  function formCandidate(){const forms=[...document.forms];const candidates=forms.map((f,i)=>({f,i,fields:[...f.querySelectorAll('input,select,textarea')].filter(e=>!e.disabled&&e.type!=='hidden'&&(visible(e)||e.type==='file'))})).filter(x=>visible(x.f)&&x.fields.some(e=>['email'].includes(e.type)||/^(email|emailaddress)$/.test(C.normalize(e.name||e.id).replace(/ /g,'')))&&x.fields.some(e=>/^(full ?name|first ?name|name|given ?name)$/.test(C.normalize(e.name||e.id))||['name','given-name'].includes(e.autocomplete)));if(candidates.length!==1)return {error:'A unique standard application form was not found. Open the page and continue manually.'};const found=candidates[0];const pageText=compact(document.title+' '+[...document.querySelectorAll('h1,h2')].map(e=>e.textContent).join(' ')+' '+found.f.innerText);if(!/application|apply|resume|résumé|career|job|curriculum vitae/i.test(pageText))return {error:'This form could not be identified as a job application.'};return found;}
  function fieldsOf(form){return [...form.querySelectorAll('input,select,textarea')].filter(e=>!e.disabled&&!['hidden','button','submit','reset','image'].includes(e.type)&&(visible(e)||e.type==='file'));}
  function setValue(el,value){const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:el instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')?.set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}
  function fingerprint(form){const text=JSON.stringify({action:form.action,fields:fieldsOf(form).map(e=>({d:descriptor(e),value:e.type==='file'?[...e.files||[]].map(f=>({name:f.name,size:f.size})):e.value,checked:e.checked})),buttons:[...form.querySelectorAll('button,input[type=submit]')].filter(visible).map(e=>({text:compact(e.innerText||e.value),disabled:e.disabled}))});let hash=2166136261;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16);}
  function inspect(form){const missing=[];const unsupported=[...form.querySelectorAll('[role=combobox],[role=checkbox],[role=radio],[contenteditable=true],iframe')].filter(e=>visible(e)&&!e.matches('select,input[type=checkbox],input[type=radio]'));if(unsupported.length)missing.push('Custom controls or embedded forms need manual review.');for(const e of fieldsOf(form)){const d=descriptor(e);if(d.required){if(e.type==='radio'){if(![...form.querySelectorAll('input[type=radio]')].some(r=>r.name===e.name&&r.checked))missing.push(d.label||d.name||'Required choice');}else if(e.type==='checkbox'&&!e.checked)missing.push(d.label||d.name||'Required checkbox');else if(e.type==='file'&&!e.files?.length)missing.push(d.label||d.name||'Required attachment');else if(!['radio','checkbox','file'].includes(e.type)&&(!String(e.value||'').trim()||!e.validity.valid))missing.push(d.label||d.name||'Required field');}else if(!e.validity.valid)missing.push(d.label||d.name||'Invalid field');}const actions=[...form.querySelectorAll('button,input[type=submit]')].filter(e=>visible(e)&&!e.disabled);const final=actions.filter(e=>/^(submit application|send application|complete application|submit resume|submit résumé|submit)$/i.test(compact(e.innerText||e.value)));if(final.length!==1)missing.push('A unique final Submit application button was not found. Multi-step flows need manual review.');return {missing:[...new Set(missing)],button:final[0],fingerprint:fingerprint(form)};}
  async function fill(profile,resume){const block=blockers();if(block)return {error:block};const candidate=formCandidate();if(candidate.error)return candidate;const {f:form,i}=candidate;const before=confirmation();let filled=0;const unverified=[];for(const el of fieldsOf(form)){const d=descriptor(el);const answer=C.fieldAnswer(d,profile,resume);if(d.required&&!answer)unverified.push(d.label||d.name||'Required answer not in your saved profile');if(el.type==='file'&&el.files?.length){if(answer?.file&&el.files[0].name!==answer.value.name)unverified.push((d.label||d.name||'Attachment')+' differs from your saved résumé');continue;}if(['radio','checkbox'].includes(el.type)&&el.checked)continue;if(!['radio','checkbox','file'].includes(el.type)&&String(el.value||'').trim()){if(answer){const current=el.tagName==='SELECT'?el.options[el.selectedIndex]?.text:el.value;if(C.normalize(current)!==C.normalize(answer.value))unverified.push((d.label||d.name||'Existing answer')+' differs from your saved profile');}continue;}if(!answer||el.readOnly)continue;try{if(answer.file){const raw=atob(answer.value.data.split(',')[1]);const bytes=new Uint8Array(raw.length);for(let n=0;n<raw.length;n++)bytes[n]=raw.charCodeAt(n);const dt=new DataTransfer();dt.items.add(new File([bytes],answer.value.name,{type:answer.value.type}));el.files=dt.files;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));filled++;}else if(el.type==='checkbox'){if(/^(yes|true|agree|i agree)$/i.test(answer.value)){el.click();filled++;}}else if(el.type==='radio'){if(C.normalize(el.value)===C.normalize(answer.value)||C.normalize([...el.labels||[]].map(l=>l.textContent).join(' '))===C.normalize(answer.value)){el.click();filled++;}}else if(el.tagName==='SELECT'){const match=[...el.options].find(o=>!o.disabled&&(C.normalize(o.text)===C.normalize(answer.value)||C.normalize(o.value)===C.normalize(answer.value)));if(match){setValue(el,match.value);filled++;}}else if(['text','email','tel','url','number','search','textarea'].includes(d.type)){setValue(el,answer.value);filled++;}}catch{/* Unsupported controls are reported by inspection. */}}
    await new Promise(resolve=>setTimeout(resolve,350));const result=inspect(form);return {filled,formIndex:i,fingerprint:result.fingerprint,missing:[...new Set([...result.missing,...unverified])],confirmationBefore:before.confirmed,hasFinalButton:!!result.button,url:location.href};}
  function commit(plan){const block=blockers();if(block)return {clicked:false,error:block};const candidate=formCandidate();if(candidate.error||candidate.i!==plan.formIndex)return {clicked:false,error:'The application form changed. Review it manually.'};const check=inspect(candidate.f);if(check.missing.length||check.fingerprint!==plan.fingerprint)return {clicked:false,error:'The form changed after filling or has unresolved fields. Review it manually.'};check.button.click();return {clicked:true};}
  function confirmation(){const text=(document.body?.innerText||'').toLowerCase();const phrases=['application submitted successfully','your application has been submitted','your application has been received','application successfully submitted','thank you for applying','thank you for your application'];const activeForm=formCandidate();return {confirmed:!blockers()&&!!activeForm.error&&phrases.some(p=>text.includes(p)),url:location.href};}
  globalThis.ApplyBot={fill,commit,confirmation};
})();
