(()=>{'use strict';const $=s=>document.querySelector(s);const show=s=>$('#status').textContent=s;const pattern=url=>{const u=new URL(url);return u.protocol+'//'+u.hostname+'/*';};let tab=null;let synced=null;
  async function permissions(){const all=await chrome.permissions.getAll();$('#permissions').replaceChildren();for(const origin of all.origins||[]){const row=document.createElement('div');row.className='permission';const label=document.createElement('span');label.textContent=origin;const b=document.createElement('button');b.textContent='Remove';b.addEventListener('click',async()=>{await chrome.permissions.remove({origins:[origin]});await permissions();show('Site access removed.');});row.append(label,b);$('#permissions').append(row);}}
  // v35: one click fills the open application with the profile and résumé the portal synced
  Promise.all([chrome.tabs.query({active:true,currentWindow:true}),chrome.storage.local.get(['synced','dashboard'])]).then(([tabs,v])=>{tab=tabs[0]||null;synced=v.synced||null;if(v.dashboard?.url)$('#dashboard').value=v.dashboard.url;
    if(!synced){$('#fill').disabled=true;$('#who').textContent='Open Application bot in your StratEdge portal once: your profile and résumé are then ready here.';}
    else $('#who').textContent='Uses '+(synced.name||'your')+'’s portal profile'+(synced.resume?' and '+synced.resume.name:'')+', updated '+new Date(synced.at).toLocaleDateString()+'. Nothing is submitted: you check the form and send it yourself.';
    let page='';try{page=tab&&/^https?:/.test(tab.url)?new URL(tab.url).hostname:'';}catch{}if(synced&&!page){$('#fill').disabled=true;}if(synced&&page&&ApplyCore.portalFor(tab.url)){$('#fill').disabled=true;$('#who').textContent='Job boards are a manual handoff: fill their forms yourself.';}});
  $('#fill').addEventListener('click',()=>{if(!tab||!synced)return;let origin;try{origin=pattern(tab.url);}catch{show('Open a job application page first.');return;}
    // the permission prompt must come straight from the click
    chrome.permissions.request({origins:[origin]}).then(async granted=>{if(!granted){show('Access to this site was not allowed.');return;}show('Filling…');const r=await chrome.runtime.sendMessage({action:'POPUP_FILL',tabId:tab.id});if(r?.error)throw Error(r.error);const x=r.result;show('Filled '+x.filled+' field'+(x.filled===1?'':'s')+'. Check everything and submit it yourself.'+(x.missing.length?' Needs you: '+x.missing.join('; '):''));await permissions();}).catch(e=>show(e.message));});
  $('#openbot').addEventListener('click',()=>chrome.tabs.create({url:synced?.portal||'https://stratedgeitconsulting.com/#/portal/appbot'}));
  $('#connect').addEventListener('click',async()=>{try{const url=ApplyCore.safeUrl($('#dashboard').value);const granted=await chrome.permissions.request({origins:[pattern(url)]});if(!granted){show('Access to the portal address was not granted.');return;}const result=await chrome.runtime.sendMessage({action:'CONFIGURE_DASHBOARD',url});if(result?.error)throw Error(result.error);await chrome.tabs.create({url});show('Connected. Reload the portal page if it does not show “Connected” yet.');await permissions();}catch(e){show(e.message);}});
  $('#grant').addEventListener('click',async()=>{try{const url=ApplyCore.safeUrl($('#employer').value);if(ApplyCore.portalFor(url))throw Error('Job boards are a manual handoff. Allow an employer’s own application site instead.');const granted=await chrome.permissions.request({origins:[pattern(url)]});show(granted?'Allowed.':'Not allowed.');await permissions();}catch(e){show(e.message);}});
  $('#stop').addEventListener('click',async()=>{await chrome.runtime.sendMessage({action:'POPUP_STOP'});show('The bot is paused.');});permissions();
})();
