<?php
declare(strict_types=1);
/*
 * v35: the built-in content of the voice practice module (api/practice.php): the call scenarios, the technical
 * question packs per skill and the listen-and-repeat sentences. Every question lists the points a good answer
 * covers (each a label and the words that show it), the answer length that sounds right on a call, an optional
 * follow-up for a missing point, and a model answer ({placeholders} come from the person's profile and the call).
 * Administrators add their own questions per scenario under Practice & training > Settings.
 */

// words that show a point (PCRE fragments, matched case-insensitively on whole words)
const PR_NUM = '\b(\$?\d{2,3}(\.\d+)?\s*(\$|dollars?|\/\s*h(ou)?r|an hour|per hour|hourly|k)?|sixty|seventy|eighty|ninety|hundred)\b';
const PR_YEARS = '\b(\d+|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|eighteen|twenty)\+?\s*(plus\s*)?(years?|yrs)\b';
const PR_VISA = '\b(h-?1-?b|h1|green card|gc|citizen|usc|opt|stem|cpt|ead|tn|l-?2|h-?4|e-?3|l-?1|permanent resident)\b';
const PR_RESULT = '\b(\d+\s*(%|percent)|reduced|improved|increased|saved|faster|on time|delivered|launched|went live|cut|grew|zero (downtime|defects))\b';
const PR_STAR_ACT = '\bi (did|decided|built|led|took|created|designed|organi[sz]ed|proposed|worked|fixed|wrote|automated|analy[sz]ed|set up|introduced|coordinated|implemented|migrated|resolved)\b';

/** The call scenarios: steps in order (the last one ends the call). */
function prScenarios(): array
{
    $greet = fn(string $who) => ['k' => 'greet', 'q' => 'Hi {first}, this is {vname} from {vco}. ' . $who . ' Is this a good time to talk for a few minutes?', 'pts' => [['you agree to talk', '\b(yes|yeah|sure|okay|ok|of course|go ahead|good time|absolutely|please|hi|hello)\b']], 'len' => [1, 40], 'model' => 'Yes, this is a good time. Thanks for calling, {vfirst}. Please go ahead.'];
    $intro = ['k' => 'intro', 'q' => 'Great. Could you give me a quick introduction about yourself?', 'pts' => [['your years of experience', PR_YEARS], ['your current or latest role', '\b(currently|current|right now|presently|working (as|at|on|with)|my (last|current|recent|latest) (project|role|client))\b'], ['your key skills', '{skillsre}'], ['what you are looking for', '\b(looking for|interested in|next (role|opportunity|project|contract)|want to|would like to)\b']], 'len' => [40, 220], 'model' => 'I am {first}, {atitle} with {years} years of experience, mainly in {skills}. In my current project I {recent}. I am looking for my next contract where I can use {skill1} on a bigger team.'];
    $project = ['k' => 'project', 'q' => 'What does your current or most recent project look like, and what exactly is your role in it?', 'pts' => [['the client or domain', '\b(client|bank|banking|health|healthcare|insurance|retail|telecom|finance|financial|government|domain|company|e-?commerce|pharma)\b'], ['what you do yourself', PR_STAR_ACT], ['the technologies', '{skillsre}'], ['a result', PR_RESULT]], 'len' => [40, 250], 'model' => 'I work for a [industry] client on a team of about eight. I own {skill1} work end to end: I designed and built the services, reviewed code and supported releases. Last quarter we cut processing time by about 30 percent.'];
    $location = ['k' => 'location', 'q' => 'Where are you located right now, and are you open to relocating or working onsite?', 'pts' => [['where you are', '\b(in|from|located|based|live|living|stay|staying)\b'], ['relocation or onsite', '\b(relocat\w*|onsite|on-site|hybrid|remote|open to|willing|commute|travel)\b']], 'len' => [6, 80], 'fu' => [1, 'And would you be open to relocating, or working onsite a few days a week?'], 'model' => 'I am in {mycity} right now. I am open to relocating for the right role, and hybrid or onsite is fine.'];
    $visa = ['k' => 'visa', 'q' => 'What is your current work authorization?', 'pts' => [['your visa or status', PR_VISA], ['validity or sponsorship', '\b(valid|until|expires?|transfer|sponsor\w*|extension|years? left|approved)\b']], 'len' => [3, 80], 'fu' => [0, 'Sorry, which visa or status are you on exactly?'], 'model' => '{visastmt}, and I can work on this contract for its full duration.'];
    $avail = ['k' => 'avail', 'q' => 'If you are selected, how soon could you start?', 'pts' => [['a start date or notice period', '\b(immediately|right away|asap|\d+\s*(weeks?|days?)|one week|two weeks|notice|next (week|month)|available (from|on|by)|monday|first of)\b']], 'len' => [3, 60], 'fu' => [0, 'Got it. So what date could you actually start?'], 'model' => 'I can start two weeks after the offer; I give my current client two weeks of notice.'];
    $rate = ['k' => 'rate', 'q' => 'What rate are you expecting for this role, and is that C2C or W2?', 'pts' => [['a number', PR_NUM], ['C2C or W2', '\b(c2c|corp to corp|corp-to-corp|w-?2|1099)\b']], 'len' => [3, 80], 'fu' => [0, 'Could you give me a number? What hourly rate do you have in mind?'], 'model' => 'For this role I am looking at {ratenum} an hour on C2C. On W2 that would be a little lower, depending on the benefits.'];
    $close = fn(string $t) => ['k' => 'close', 'q' => $t, 'end' => true];
    return [
        'vendor' => [
            't' => 'Vendor screening call',
            'd' => 'A recruiter at a staffing vendor checks your background, location, visa, availability and rate for a contract role, then asks for the Right to Represent.',
            'who' => 'Recruiter',
            'steps' => [
                $greet('I am calling about a {role} contract with {client} in {city}.'),
                $intro,
                $project,
                $location,
                $visa,
                $avail,
                $rate,
                ['k' => 'other', 'q' => 'Have you been submitted to {client} by any other vendor recently?', 'pts' => [['a clear yes or no', '\b(no|not|haven\'?t|have not|never|yes|already)\b']], 'len' => [1, 60], 'model' => 'No, nobody has submitted me to {client} in the last six months.'],
                ['k' => 'rtr', 'q' => 'Okay. I will email you a Right to Represent for this position. Can you reply to confirm it today?', 'pts' => [['you agree to confirm', '\b(yes|sure|will|confirm|reply|okay|ok|send)\b'], ['you check the details', '\b(rate|client|duration|details|terms|position|check|review|read)\b']], 'len' => [1, 80], 'model' => 'Sure, please send it. I will check the client, the rate and the duration and reply today.'],
                ['k' => 'ask', 'q' => 'Do you have any questions for me about the role?', 'pts' => [['a question about the role', '\b(duration|how long|extension|interview|process|team|start|project|client|remote|onsite|hours|rate|next steps?|timeline|rounds?)\b']], 'len' => [3, 120], 'model' => 'Yes: how long is the contract and is there an extension, how many interview rounds are there, and when do you expect feedback?'],
                $close('Thanks {first}. I will send the details and the RTR now and get back to you once I hear from the client. Have a great day!'),
            ],
        ],
        'tech' => [
            't' => 'Technical screen',
            'd' => 'A technical lead at the implementation partner asks about your project and your {skillname} skills, then a production issue and how you ship code.',
            'who' => 'Technical lead',
            'steps' => [
                $greet('I am the technical lead for the {role} position with {client}, and I have about fifteen minutes.'),
                array_merge($intro, ['q' => 'To start, give me a short summary of your experience with {skillname}.', 'len' => [30, 180]]),
                ['k' => 'tech'],
                ['k' => 'tech'],
                ['k' => 'tech'],
                ['k' => 'tech'],
                ['k' => 'issue', 'q' => 'Tell me about a production issue or a tough bug you handled. What did you do?', 'pts' => [['the problem', '\b(issue|bug|outage|incident|error|failure|slow|crash|down|defect|problem)\b'], ['what you did', '\bi (found|checked|debugged|analy[sz]ed|traced|fixed|rolled back|wrote|added|reproduced|looked)\b'], ['the result', PR_RESULT . '|\b(fixed|resolved|restored|stable)\b'], ['how you prevented it again', '\b(learn\w*|prevent\w*|monitor\w*|alert\w*|test\w*|post-?mortem|root cause|runbook)\b']], 'len' => [50, 250], 'model' => 'Our nightly job started failing after a release. I reproduced it in staging, traced it in the logs to a schema change, rolled back, then fixed the query and added a test and an alert. Since then it has not failed.', 'tech' => true],
                ['k' => 'process', 'q' => 'How do you test and deploy your code on your current team?', 'pts' => [['testing', '\b(unit|integration|tests?|qa|automation|junit|pytest|selenium|coverage)\b'], ['the pipeline', '\b(ci|cd|ci\/cd|pipeline|jenkins|github actions|azure devops|gitlab|deploy\w*|release)\b'], ['code review', '\b(git|pull requests?|code reviews?|branch\w*|merge)\b']], 'len' => [30, 200], 'model' => 'Every change has unit tests and goes through a pull request with a code review. Jenkins builds it, runs the tests and deploys to QA, and after sign-off the same pipeline releases to production.', 'tech' => true],
                $close('That is all from my side, {first}. Thanks for your time; the recruiter will let you know about the next round.'),
            ],
        ],
        'client' => [
            't' => 'Client manager interview',
            'd' => 'The hiring manager asks behavioral questions (answer with the situation, what you did and the result), one technical question and why you.',
            'who' => 'Hiring manager',
            'steps' => [
                $greet('I am the hiring manager for the {role} role, thanks for joining.'),
                $intro,
                ['k' => 'challenge', 'q' => 'Tell me about the most challenging project you worked on. What was the situation, what did you do, and what was the result?', 'pts' => [['the situation', '\b(situation|project|client|team|when|we had|there was|deadline)\b'], ['your actions', PR_STAR_ACT], ['the result', PR_RESULT]], 'len' => [60, 260], 'model' => 'We had to move a payments service to the cloud in three months. I planned the migration in phases, built the new services and ran both systems side by side. We went live on time with no downtime and cut costs by about 25 percent.'],
                ['k' => 'conflict', 'q' => 'Tell me about a time you disagreed with a teammate or your manager. How did you handle it?', 'pts' => [['you listened first', '\b(listen\w*|understand\w*|perspective|heard|asked)\b'], ['you used data or discussion', '\b(data|discuss\w*|meeting|compromise|proposal|tested|showed|prototype|numbers)\b'], ['you kept the relationship', '\b(respect\w*|team|relationship|agreed|moved forward|together)\b']], 'len' => [50, 220], 'model' => 'A teammate wanted to add caching everywhere. I listened to the reasons, then we measured the slow calls together and showed that two endpoints caused most of the delay. We cached only those, agreed on it as a team and still work well together.'],
                ['k' => 'deadline', 'q' => 'How do you handle a tight deadline when the requirements keep changing?', 'pts' => [['you prioritise', '\b(prioriti[sz]\w*|must.have|scope|important)\b'], ['you communicate early', '\b(communicat\w*|inform\w*|update\w*|stakeholders?|manager|escalat\w*)\b'], ['you plan the work', '\b(plan\w*|break\w*|tasks?|estimat\w*|sprints?)\b']], 'len' => [40, 200], 'model' => 'I agree with the product owner what is a must-have, break it into small tasks and tell the stakeholders early what will and will not fit, so there are no surprises at the deadline.'],
                ['k' => 'tech'],
                ['k' => 'why', 'q' => 'Why should we choose you for this role?', 'pts' => [['your matching experience', PR_YEARS . '|\b(experience\w*|done this|similar)\b'], ['specific skills', '{skillsre}'], ['the value you bring', '\b(deliver\w*|value|help|contribute|quick\w*|ramp up|ownership|reliable)\b']], 'len' => [30, 180], 'model' => 'I have {years} years of {skill1} work on projects like yours, I ramp up quickly and I take ownership, so you get someone who delivers from the first sprint.'],
                ['k' => 'ask', 'q' => 'What questions do you have for me?', 'pts' => [['a question about the team or the work', '\b(team|project|success|challenges?|next steps?|expect\w*|first (month|weeks?|90 days)|culture|stack)\b']], 'len' => [3, 120], 'model' => 'What would success look like in the first ninety days, and what is the biggest challenge the team has right now?'],
                $close('Thank you {first}, this was helpful. We will get back to your vendor this week.'),
            ],
        ],
        'rate' => [
            't' => 'Rate negotiation',
            'd' => 'The vendor says the client budget is lower than your rate. Keep your value, counter with a number and close politely.',
            'who' => 'Recruiter',
            'steps' => [
                $greet('Good news: {client} liked your profile for the {role} role.'),
                ['k' => 'rate', 'q' => 'Before I confirm you, what is your rate for this role, and is it C2C or W2?'] + $rate,
                ['k' => 'push', 'q' => 'Honestly, the client budget is around {lowrate} an hour. Can you work with that?', 'pts' => [['a number (a counter or a yes)', PR_NUM], ['why you are worth it', '\b(experience\w*|years|skills?|market|value|certif\w*|delivered|expertise|fair|senior)\b'], ['a positive tone', '\b(understand\w*|appreciate|thanks?|happy|flexible|open|work with you|meet)\b']], 'len' => [15, 160], 'model' => 'I understand the budget. With {years} years in {skill1} I am usually at {ratenum}; I can come down to {midrate} an hour if the duration is twelve months. Would that work?'],
                ['k' => 'agree', 'q' => 'If I can get you {midrate} an hour, can you confirm today?', 'pts' => [['a clear decision', '\b(yes|no|agree\w*|confirm\w*|accept\w*|works?|deal|okay|ok|fine)\b'], ['the terms', '\b(duration|extension|start|c2c|w-?2|net\s*\d+|payment|invoice|hours|months?)\b']], 'len' => [5, 120], 'model' => 'Yes, {midrate} an hour on C2C works for a twelve-month contract with net-30 payment. Please send the RTR with those terms and I will confirm today.'],
                $close('Perfect, {first}. I will send the RTR with those terms in a few minutes. Thanks!'),
            ],
        ],
        'visa' => [
            't' => 'Visa and documents',
            'd' => 'Questions about your work authorization, its validity, transfers, onboarding documents and your employer.',
            'who' => 'Recruiter',
            'steps' => [
                $greet('Before I submit you for the {role} role, I need to check a few compliance details.'),
                $visa,
                ['k' => 'validity', 'q' => 'Is your authorization valid for the whole contract, and would you need a transfer or sponsorship?', 'pts' => [['how long it is valid', '\b(valid|until|expires?|years?|months?|extension|approved till)\b'], ['transfer or sponsorship', '\b(transfer|sponsor\w*|no sponsorship|not need|need|petition)\b']], 'len' => [6, 120], 'model' => 'Yes, it is valid until {visayear}, which covers the contract, and I do not need sponsorship or a transfer for this role.'],
                ['k' => 'i9', 'q' => 'For onboarding, which documents can you provide for the I-9?', 'pts' => [['identity and work documents', '\b(passport|ead|green card|driver\'?s?|licen[cs]e|social security|ssn card|i-?94|i-?797|state id|approval notice)\b']], 'len' => [5, 120], 'model' => 'I can provide my passport with the I-94 and my approval notice, and my driver license and Social Security card if you need List B and C documents.'],
                ['k' => 'employer', 'q' => 'Who is your employer of record right now, and can they work C2C?', 'pts' => [['your employer', '\b(employer|company|corp|inc|llc|consulting|solutions|w-?2 with|work for|working for)\b'], ['C2C or W2', '\b(c2c|corp to corp|w-?2|yes|no)\b']], 'len' => [4, 100], 'model' => 'My employer is my current consulting company and they work C2C with vendors; I can share their contact for the paperwork.'],
                ['k' => 'gaps', 'q' => 'Have you had any gaps in status, or is anything pending that we should know about?', 'pts' => [['a clear answer', '\b(no gaps?|never|pending|approved|receipt|rfe|filed|yes|no|nothing)\b']], 'len' => [3, 100], 'model' => 'No gaps in status, and nothing is pending right now.'],
                $close('That covers it, {first}. Thanks for the quick answers; I will submit you today.'),
            ],
        ],
        'intro' => [
            't' => 'Tell me about yourself',
            'd' => 'The answer every call starts with. Aim for 60 to 90 seconds: who you are, your experience and skills, your current work and what you want next.',
            'who' => 'Recruiter',
            'steps' => [
                array_merge($intro, ['q' => 'Hi {first}, this is {vname} from {vco}. Before we talk about the role, tell me about yourself.', 'len' => [60, 230]]),
                $close('Thank you, {first}. That gives me a good picture.'),
            ],
        ],
    ];
}

/** Technical question packs: 5 questions per skill, each with its points and a model answer. */
function prSkillPacks(): array
{
    $q = fn(string $q, array $pts, string $model) => ['q' => $q, 'pts' => $pts, 'len' => [25, 220], 'model' => $model, 'tech' => true];
    return [
        'java' => ['n' => 'Java', 'match' => '\b(java|spring|j2ee|jee|hibernate|microservices)\b', 'role' => 'Senior Java Developer', 'qs' => [
            $q('What is the difference between an interface and an abstract class in Java?', [['many interfaces, one parent class', '\b(multiple|many|more than one|single (inheritance|parent))\b'], ['state and constructors', '\b(state|fields?|constructors?|instance variables?)\b'], ['default methods since Java 8', '\b(default methods?|java 8|static methods?)\b']], 'A class can implement many interfaces but extend only one abstract class. An abstract class can hold state and constructors; an interface cannot hold instance state, and since Java 8 it can have default and static methods. I use an interface for a contract and an abstract class to share code.'),
            $q('How does a HashMap work internally?', [['hashCode', '\b(hash ?codes?|hashing|hash)\b'], ['buckets', '\b(buckets?|array|index)\b'], ['equals on a collision', '\b(equals|collisions?)\b'], ['linked lists, trees and resizing', '\b(linked lists?|trees?|red.black|resiz\w*|load factor|rehash\w*)\b']], 'It hashes the key with hashCode to pick a bucket in an array. Keys that land in the same bucket are compared with equals and kept in a linked list, which turns into a tree when it grows past eight entries. When the map passes its load factor of 0.75 it resizes and rehashes.'),
            $q('How does Spring Boot auto-configuration work?', [['starters', '\bstarters?\b'], ['what is on the classpath', '\bclasspath\b'], ['conditional beans', '\b(conditional\w*|@conditional\w*|on ?missing ?bean)\b'], ['overriding with properties', '\b(propert\w*|application\.(yml|properties)|yaml)\b']], 'A starter brings the libraries; Spring Boot looks at what is on the classpath and creates beans through conditional configuration classes, for example a DataSource only when a JDBC driver is there and I have not defined my own. I override the defaults with application properties or my own beans.'),
            $q('How would you make a REST API secure?', [['HTTPS', '\b(https|tls|ssl)\b'], ['authentication with tokens', '\b(oauth\w*|jwt|tokens?|spring security|authenticat\w*)\b'], ['input validation', '\b(validat\w*|sanitiz\w*|injection)\b'], ['authorisation and rate limits', '\b(roles?|authori[sz]\w*|rate limit\w*|throttl\w*)\b']], 'HTTPS everywhere, OAuth2 with JWT tokens through Spring Security, role checks on every endpoint, validation of every input to stop injection, and rate limiting with logging and alerts for abuse.'),
            $q('What are microservices, and when would you not use them?', [['independently deployable', '\b(independent\w*|deploy\w*|own database)\b'], ['small with one responsibility', '\b(single responsib\w*|small|bounded context|domain)\b'], ['the trade-offs', '\b(complex\w*|overhead|network|monolith|small team|latency|distributed)\b']], 'Small services, each owning one business capability and its data, deployed independently. I would not use them for a small team or a simple product: a modular monolith avoids the network calls, distributed transactions and operations overhead.'),
        ]],
        'dotnet' => ['n' => '.NET', 'match' => '(\.net|\bc#|\basp\.?net|\bdotnet|\bentity framework|\bblazor)', 'role' => 'Senior .NET Developer', 'qs' => [
            $q('What is the difference between .NET Framework and .NET Core or .NET 8?', [['cross-platform', '\b(cross.platform|linux|mac|containers?)\b'], ['faster and modern', '\b(performance|faster|modern|open source|lightweight)\b'], ['Framework is Windows-only and legacy', '\b(windows|legacy|maintenance|older)\b']], '.NET Framework is the older Windows-only runtime, now only maintained. .NET Core and .NET 8 are open source, cross-platform, faster and run well in containers, so new work goes there.'),
            $q('Explain dependency injection in ASP.NET Core.', [['the built-in container', '\b(container|iservicecollection|services\.add\w*|built.in)\b'], ['lifetimes', '\b(singleton|scoped|transient|lifetimes?)\b'], ['constructor injection and testing', '\b(constructor|test\w*|mock\w*|loose\w*)\b']], 'Services are registered in the built-in container with a lifetime: singleton, scoped per request or transient. Classes receive them through their constructors, which keeps them loosely coupled and easy to unit test with mocks.'),
            $q('What does async and await do, and why use it?', [['it does not block', '\b(non.blocking|block\w*|threads?|free)\b'], ['Task', '\btasks?\b'], ['scalability for I/O', '\b(scal\w*|i\/o|io|database|http|requests?)\b']], 'It lets a method wait for I/O like a database or HTTP call without blocking the thread: the method returns a Task and the thread serves other requests meanwhile, so the API scales better under load.'),
            $q('How do you keep Entity Framework fast?', [['tracking off for reads', '\b(asnotracking|no.tracking|tracking)\b'], ['avoid N+1 queries', '\b(n\+1|include|eager|lazy)\b'], ['check the SQL and indexes', '\b(sql|indexes?|profil\w*|query plan|projection|select)\b']], 'AsNoTracking for read-only queries, Include or projections to avoid N+1 queries, selecting only the columns needed, and checking the generated SQL and indexes with a profiler.'),
            $q('How do you secure an ASP.NET Core Web API?', [['HTTPS', '\b(https|tls|ssl)\b'], ['authentication with tokens', '\b(jwt|oauth\w*|tokens?|azure ad|entra|identity)\b'], ['authorisation policies', '\b(authori[sz]\w*|policies|roles?|claims)\b'], ['validation', '\b(validat\w*|sanitiz\w*|injection)\b']], 'HTTPS only, JWT bearer tokens from Azure AD, authorization policies based on roles and claims on every controller, model validation on every input, and secrets in Key Vault.'),
        ]],
        'python' => ['n' => 'Python', 'match' => '\b(python|django|flask|fastapi|pandas)\b', 'role' => 'Python Developer', 'qs' => [
            $q('What is the difference between a list and a tuple?', [['mutable versus immutable', '\b(mutable|immutable|change\w*)\b'], ['hashable, so a dictionary key', '\b(hashable|dict\w* keys?|keys?)\b'], ['memory and speed', '\b(memory|faster|performance|lighter)\b']], 'A list is mutable and a tuple is immutable. Because a tuple cannot change it is hashable, so it can be a dictionary key, and it uses a little less memory.'),
            $q('What is a decorator in Python?', [['a function that wraps a function', '\b(wrap\w*|function|callable)\b'], ['the @ syntax', '(@|\bat sign\b|\bsyntax\b)'], ['what it is used for', '\b(logging|auth\w*|caching|retry|timing|validation)\b']], 'A decorator is a function that takes another function and returns a wrapped version, applied with the @ syntax. I use them for logging, retries, caching and checking permissions without repeating that code.'),
            $q('How do you manage dependencies and environments?', [['virtual environments', '\b(venv|virtualenv|conda|poetry|pipenv|virtual)\b'], ['a requirements file', '\b(requirements|pyproject|lock\w*|pip)\b'], ['pinned versions', '\b(pin\w*|versions?|reproducib\w*)\b']], 'Each project gets its own virtual environment, dependencies are listed in pyproject or requirements files with pinned versions, and the lock file keeps builds reproducible in CI and Docker.'),
            $q('What is the GIL, and how does it affect concurrency?', [['one thread runs Python code at a time', '\b(one thread|single thread|lock|bytecode|gil)\b'], ['processes for CPU work', '\b(multiprocessing|processes|cpu)\b'], ['threads or asyncio for I/O', '\b(threads?|asyncio|async|i\/o|io)\b']], 'The global interpreter lock lets only one thread run Python bytecode at a time. For CPU-heavy work I use multiprocessing; for I/O-bound work threads or asyncio work well because the lock is released while waiting.'),
            $q('How would you build a REST API in Python?', [['the framework', '\b(fastapi|flask|django)\b'], ['validation', '\b(pydantic|serializ\w*|validat\w*|schemas?)\b'], ['tests and deployment', '\b(pytest|tests?|docker|deploy\w*|gunicorn|uvicorn)\b']], 'With FastAPI: Pydantic models validate every request and response, endpoints are tested with pytest, and it runs in Docker behind Uvicorn and Gunicorn.'),
        ]],
        'data' => ['n' => 'Data engineering & SQL', 'match' => '\b(sql|etl|data engineer\w*|spark|snowflake|informatica|databricks|airflow|power bi|tableau|data warehouse|hadoop|azure data factory|adf|redshift|bigquery)\b', 'role' => 'Data Engineer', 'qs' => [
            $q('What is the difference between a star schema and a snowflake schema?', [['facts and dimensions', '\b(facts?|dimensions?)\b'], ['normalised dimensions', '\b(normali[sz]\w*|split|sub.dimensions?)\b'], ['joins and query speed', '\b(joins?|performance|faster|simpl\w*)\b']], 'Both have a fact table with measures surrounded by dimensions. In a star schema the dimensions are flat; in a snowflake schema they are normalised into more tables, which saves space but needs more joins, so star queries are usually simpler and faster.'),
            $q('How do you handle slowly changing dimensions?', [['type 1 overwrites', '\b(type ?1|overwrit\w*)\b'], ['type 2 keeps history', '\b(type ?2|history|effective dates?|valid from|current flag)\b'], ['surrogate keys', '\b(surrogate keys?)\b']], 'Type 1 overwrites the old value when history does not matter. Type 2 adds a new row with effective dates and a current flag, using surrogate keys so the facts point to the version that was true at the time.'),
            $q('How do you speed up a slow SQL query?', [['read the execution plan', '\b(execution plan|explain|query plan)\b'], ['indexes', '\bindex\w*\b'], ['filter early and avoid select star', '\b(select \*|filter\w*|where|partition\w*|predicate)\b'], ['statistics and rewriting', '\b(statistics|stats|rewrite|cte|temp tables?)\b']], 'I read the execution plan first, add or fix indexes for the joins and filters, filter early instead of selecting everything, use partitions for big tables, and update statistics or rewrite the query if the plan is still poor.'),
            $q('How does Spark process data, and what causes a shuffle?', [['distributed partitions', '\b(partitions?|executors?|distributed|cluster)\b'], ['lazy evaluation', '\b(lazy|dag|transformations?|actions?)\b'], ['joins and group-bys shuffle', '\b(joins?|group ?by|repartition|aggregat\w*|shuffle)\b']], 'Spark splits the data into partitions processed by executors in parallel. Transformations are lazy and build a DAG that runs when an action is called. Wide operations like joins, group-bys and repartition move data between executors, which is the shuffle.'),
            $q('How do you make a data pipeline reliable?', [['idempotent and retryable', '\b(idempotent|retr\w*|rerun\w*|restart\w*)\b'], ['data quality checks', '\b(quality|validat\w*|checks?|tests?)\b'], ['monitoring and alerts', '\b(monitor\w*|alert\w*|logg\w*)\b'], ['orchestration', '\b(airflow|adf|data factory|orchestrat\w*|schedul\w*)\b']], 'Every step is idempotent so a failed run can simply be retried, data quality checks stop bad data early, Airflow orchestrates and retries, and monitoring alerts us before the business notices.'),
        ]],
        'devops' => ['n' => 'DevOps & cloud', 'match' => '\b(devops|aws|azure|gcp|kubernetes|k8s|docker|terraform|jenkins|ci\/cd|cloud|ansible|sre)\b', 'role' => 'DevOps Engineer', 'qs' => [
            $q('What happens in your CI/CD pipeline from commit to production?', [['build and tests', '\b(build\w*|tests?|unit)\b'], ['artifacts or images', '\b(artifacts?|images?|registry|docker|containers?)\b'], ['stages, approvals and rollback', '\b(stages?|approvals?|rollback|roll back|blue.green|canary|production)\b']], 'A commit triggers a build that runs the tests and scans, produces a Docker image pushed to the registry, deploys to dev and QA automatically, and goes to production after approval with a blue-green switch so we can roll back quickly.'),
            $q('What is the difference between a Docker image and a container?', [['an image is a template', '\b(template|layers?|read.only|blueprint)\b'], ['a container is a running instance', '\b(running|instance|process)\b'], ['the registry', '\b(registry|docker ?hub|ecr|acr)\b']], 'An image is the read-only template built in layers from a Dockerfile and stored in a registry; a container is a running instance of that image with its own writable layer.'),
            $q('How does Kubernetes keep an application running?', [['desired state', '\b(desired state|controllers?|reconcil\w*)\b'], ['replicas and health checks', '\b(replicas?|deployments?|liveness|readiness|probes?|health)\b'], ['self-healing and services', '\b(restart\w*|reschedul\w*|self.heal\w*|services?)\b']], 'You declare the desired state in a Deployment; controllers keep the replica count, liveness and readiness probes restart or remove unhealthy pods, failed nodes get their pods rescheduled, and a Service keeps routing traffic to the healthy ones.'),
            $q('What is infrastructure as code, and which tools have you used?', [['infrastructure defined in code', '\b(code|version control\w*|git|repeatable)\b'], ['the tools', '\b(terraform|cloudformation|arm|bicep|ansible|pulumi)\b'], ['plan, state and review', '\b(plan|state|review|modules?)\b']], 'Infrastructure is defined in code kept in Git, so environments are repeatable and reviewed like any change. I use Terraform modules: every change runs a plan in the pipeline, is reviewed, then applied, with remote state.'),
            $q('How do you keep secrets safe in the cloud?', [['a secrets manager', '\b(vault|secrets? manager|key vault|parameter store)\b'], ['never in code, rotated', '\b(not in (the )?code|rotat\w*|environment|git)\b'], ['least privilege', '\b(iam|least privilege|roles?|permissions?)\b']], 'Secrets live in a secrets manager like AWS Secrets Manager or Key Vault, never in code or Git; applications read them at runtime with IAM roles that have the least privilege, and they are rotated automatically.'),
        ]],
        'salesforce' => ['n' => 'Salesforce', 'match' => '\b(salesforce|apex|lwc|lightning|sfdc|visualforce)\b', 'role' => 'Salesforce Developer', 'qs' => [
            $q('What are governor limits, and how do you work within them?', [['limits because it is multi-tenant', '\b(multi.tenant|limits?|soql|dml)\b'], ['bulkified code', '\b(bulk\w*|collections?|lists?|maps?)\b'], ['no queries in loops, async work', '\b(loops?|batch|queueable|future|async\w*)\b']], 'Because Salesforce is multi-tenant it limits each transaction, for example 100 SOQL queries. I bulkify code with collections and maps, never query or update inside loops, and move heavy work to Batch or Queueable Apex.'),
            $q('When would you use a trigger instead of a flow?', [['flows first', '\b(declarative|flows?|clicks?)\b'], ['triggers for complex or bulk logic', '\b(complex|bulk|performance|apex)\b'], ['one trigger per object', '\b(one trigger|handler|framework)\b']], 'I start with a flow when it is simple and admins can maintain it. For complex or high-volume logic I use an Apex trigger, one per object, calling a handler class.'),
            $q('What are Lightning Web Components?', [['web standards', '\b(web standards?|javascript|html|custom elements)\b'], ['getting data from Apex', '\b(apex|wire|imperative|lds)\b'], ['events between components', '\b(events?|communicat\w*|pub.?sub|lms)\b']], 'They are components built on web standards with HTML and JavaScript. Data comes from Lightning Data Service or Apex through wire or imperative calls, and components talk through events and the Lightning Message Service.'),
            $q('How do you control who can see which data?', [['profiles and permission sets', '\b(profiles?|permission sets?)\b'], ['sharing settings', '\b(owd|org.wide|sharing rules?|role hierarchy)\b'], ['field-level security', '\b(field.level|fls)\b']], 'Profiles and permission sets give object and field access, organization-wide defaults set the baseline, and the role hierarchy and sharing rules open records up from there, with field-level security for sensitive fields.'),
            $q('How do you deploy changes between orgs?', [['the tools', '\b(change sets?|sfdx|sf cli|devops center|copado|gearset|ant)\b'], ['sandboxes', '\b(sandbox\w*|scratch orgs?)\b'], ['tests and coverage', '\b(tests?|coverage|75)\b']], 'With Salesforce DX from source control through the sandboxes into production, running all tests with at least 75 percent coverage, using DevOps Center or Gearset for the promotions.'),
        ]],
        'qa' => ['n' => 'QA & test automation', 'match' => '\b(qa|test\w*|selenium|automation|cypress|playwright|appium|sdet)\b', 'role' => 'QA Automation Engineer', 'qs' => [
            $q('Explain the test automation pyramid.', [['many unit tests', '\bunit\b'], ['fewer API or service tests', '\b(api|service|integration)\b'], ['few UI tests', '\b(ui|end.to.end|e2e|slow|flaky)\b']], 'Most automated tests should be fast unit tests, fewer at the API and service level, and only a few end-to-end UI tests, because UI tests are slow and flaky.'),
            $q('How do you handle waiting in Selenium?', [['explicit waits', '\b(explicit wait\w*|webdriverwait|wait until)\b'], ['no fixed sleeps', '\b(thread\.sleep|sleep|implicit)\b'], ['expected conditions', '\b(expected conditions?|visible|clickable)\b']], 'With explicit waits: WebDriverWait with expected conditions like element clickable, never fixed sleeps, and I do not mix implicit and explicit waits.'),
            $q('How do you test an API?', [['status codes and body', '\b(status codes?|response|body|schema|json)\b'], ['the tools', '\b(postman|rest.?assured|newman|karate|pytest)\b'], ['negative and security cases', '\b(negative|edge cases?|invalid|auth\w*|security)\b']], 'I check the status codes, response body and schema for valid requests, then negative and edge cases and authorization, automated with RestAssured in the pipeline.'),
            $q('Describe the life cycle of a bug.', [['new and assigned', '\b(new|assigned|open)\b'], ['fixed and retested', '\b(fixed|retest\w*|verified)\b'], ['closed or reopened, severity', '\b(closed|reopen\w*|severity|priority)\b']], 'A bug is logged as new with steps, severity and priority, assigned to a developer, fixed, retested by QA, then closed or reopened if it still fails.'),
            $q('How do you decide what to automate?', [['repetitive regression tests', '\b(regression|repetit\w*|repeat\w*)\b'], ['stable features', '\b(stable|mature)\b'], ['value and risk', '\b(roi|value|risk|critical|not one.off)\b']], 'Stable, repetitive regression scenarios with high business risk come first; one-off checks and fast-changing screens stay manual until they settle.'),
        ]],
        'ba' => ['n' => 'Business analysis', 'match' => '\b(business analyst|\bba\b|requirements|product owner|scrum master|functional)\b', 'role' => 'Business Analyst', 'qs' => [
            $q('How do you gather requirements from stakeholders?', [['interviews and workshops', '\b(interviews?|workshops?|meetings?|observ\w*|shadow\w*)\b'], ['documenting them', '\b(document\w*|user stor\w*|brd|frd|specs?)\b'], ['validating and prioritising', '\b(validat\w*|sign.off|prioriti[sz]\w*|confirm\w*)\b']], 'I run interviews and workshops with each stakeholder group, write user stories with acceptance criteria, and walk them back through it to validate and prioritise before sign-off.'),
            $q('What makes a good user story?', [['as a, I want, so that', '\b(as a|i want|so that)\b'], ['acceptance criteria', '\bacceptance criteria\b'], ['small and testable', '\b(invest|small|testable|independent|estimable)\b']], 'It says who wants what and why, as a, I want, so that, has clear acceptance criteria and follows INVEST: small, independent and testable.'),
            $q('How do you handle conflicting requirements?', [['understand the reasons', '\b(understand\w*|why|root|goals?)\b'], ['bring people together', '\b(meeting|facilitat\w*|workshop|trade.offs?)\b'], ['a decision on record', '\b(decision|document\w*|sponsor|priorit\w*)\b']], 'I find out what each side needs and why, bring them together to look at the trade-offs against the business goals, and get the sponsor to decide, which I document.'),
            $q('What is UAT, and what is your role in it?', [['business users validate', '\b(business users?|end users?|validat\w*|acceptance)\b'], ['test scenarios', '\b(test cases?|scenarios?|scripts?)\b'], ['defects and sign-off', '\b(defects?|bugs?|sign.off)\b']], 'User acceptance testing is where business users confirm the solution meets their needs. I prepare the scenarios from the stories, support the testers, triage defects and get the sign-off.'),
            $q('Which tools and diagrams do you use?', [['the tools', '\b(jira|confluence|azure devops|excel|power bi|sql)\b'], ['process diagrams', '\b(process flows?|bpmn|visio|swim ?lanes?|lucid\w*)\b'], ['data work', '\b(sql|data|queries|excel|reports?)\b']], 'Jira and Confluence for stories and documentation, Visio or Lucidchart for BPMN process flows with swimlanes, and SQL and Excel to check the data.'),
        ]],
        'network' => ['n' => 'Networking & security', 'match' => '\b(network\w*|cisco|bgp|ospf|firewalls?|ccna|ccnp|palo alto|fortinet|sd.?wan|routing|switching|security engineer)\b', 'role' => 'Network Engineer', 'qs' => [
            $q('What is the difference between OSPF and BGP?', [['interior versus exterior', '\b(interior|exterior|igp|egp|inside|between)\b'], ['link state versus path vector', '\b(link.state|path.vector|dijkstra|spf)\b'], ['autonomous systems and attributes', '\b(autonomous systems?|as|attributes?|policy|isp)\b']], 'OSPF is a link-state interior protocol inside one network using Dijkstra; BGP is a path-vector exterior protocol between autonomous systems, chosen by attributes and policy, used with ISPs and large WANs.'),
            $q('How do VLANs work, and why use them?', [['they split broadcast domains', '\b(broadcast|layer ?2|segment\w*)\b'], ['trunks and tagging', '\b(trunk\w*|802\.1q|tag\w*)\b'], ['security and routing between them', '\b(secur\w*|inter.vlan|routing|isolat\w*)\b']], 'A VLAN splits one switch into separate layer-2 broadcast domains. Trunks carry several VLANs with 802.1Q tags, and traffic between VLANs goes through a router or layer-3 switch, which keeps segments isolated and secure.'),
            $q('Walk me through troubleshooting a site that cannot reach an application.', [['layer by layer', '\b(layers?|osi|physical|ping|interface)\b'], ['DNS and routing', '\b(dns|routing|routes?|traceroute|tracert)\b'], ['firewalls and logs', '\b(firewalls?|acls?|logs?|rules?)\b']], 'I go layer by layer: check the link and interfaces, ping the gateway, test DNS resolution, traceroute to find where it stops, then check routes and the firewall rules and logs on the path.'),
            $q('How are firewall rules evaluated?', [['top-down, first match', '\b(top.down|first match|order)\b'], ['implicit deny', '\b(implicit deny|deny all|default deny)\b'], ['stateful zones and NAT', '\b(stateful|zones?|nat|sessions?)\b']], 'Top-down, and the first matching rule wins, with an implicit deny at the end. Modern firewalls are stateful and zone-based, so return traffic of an allowed session passes, and NAT is evaluated alongside.'),
            $q('What is SD-WAN?', [['an overlay over several links', '\b(overlay|mpls|internet|broadband|lte|links?)\b'], ['central management', '\b(central\w*|controller|orchestrat\w*|policies)\b'], ['application-aware routing', '\b(application.aware|path selection|steer\w*|cost)\b']], 'SD-WAN builds an overlay across several links like MPLS, broadband and LTE, managed from a central controller that applies policies and steers each application over the best path, cutting cost and improving performance.'),
        ]],
        'general' => ['n' => 'General IT', 'match' => '.', 'role' => 'IT Consultant', 'qs' => [
            $q('How does your team work in Agile?', [['sprints', '\b(sprints?|scrum|kanban)\b'], ['the ceremonies', '\b(stand.?ups?|planning|retro\w*|reviews?)\b'], ['stories and estimates', '\b(stor\w*|jira|estimat\w*|points)\b']], 'We run two-week Scrum sprints with planning, daily stand-ups, a review and a retrospective; work is in Jira as user stories estimated in points.'),
            $q('How do you use Git on a team?', [['branches', '\bbranch\w*\b'], ['pull requests and reviews', '\b(pull requests?|merge requests?|code reviews?|prs?)\b'], ['conflicts and merging', '\b(conflicts?|rebase|merge)\b']], 'Each change gets a feature branch, goes through a pull request with a code review and passing checks, and I rebase on main to resolve conflicts before merging.'),
            $q('How do you debug a problem you have never seen before?', [['reproduce it', '\breproduc\w*\b'], ['logs and the debugger', '\b(logs?|debugg\w*|breakpoints?)\b'], ['isolate the root cause, test the fix', '\b(isolat\w*|root cause|narrow\w*|test\w*)\b']], 'First I reproduce it, then read the logs and step through with a debugger, narrowing it down until I find the root cause, and I add a test with the fix so it does not come back.'),
            $q('How do you keep your skills up to date?', [['courses and certifications', '\b(courses?|certif\w*|training)\b'], ['hands-on practice', '\b(projects?|practi\w*|hands.on|labs?)\b'], ['the community', '\b(community|blogs?|meetups?|conferences?|podcasts?)\b']], 'I take one certification or course a year, build small side projects to try new tools hands-on, and follow blogs and meetups in my field.'),
            $q('How do you explain a technical issue to someone non-technical?', [['plain words', '\b(simple|plain|no jargon|analog\w*|non.technical)\b'], ['the business impact', '\b(impact|business|customers?|users?|cost)\b'], ['options and next steps', '\b(options?|next steps?|plan|decision)\b']], 'In plain words, starting with the impact on their users or the business, then the options and what I recommend as the next step.'),
        ]],
    ];
}

/** Listen-and-repeat sentence sets ({placeholders} from the profile). */
function prRepeatSets(): array
{
    return [
        'intro' => ['n' => 'My introduction', 's' => ['Hi, I am {first}, {atitle} with {years} years of experience.', 'I mainly work with {skills}.', 'In my current project I {recent}.', 'I am looking for my next contract where I can add value from the first sprint.']],
        'calls' => ['n' => 'Vendor call phrases', 's' => ['Yes, this is a good time. Please go ahead.', 'I am available to start two weeks after the offer.', 'My rate for this role is {ratenum} an hour on C2C.', 'Please send the Right to Represent and I will confirm today.', 'How long is the contract, and is there a possibility of an extension?', 'Could you share the job description and the client name?']],
        'visa' => ['n' => 'Work authorization', 's' => ['{visastmt}, and I can work for the full duration of the contract.', 'I do not need sponsorship for this role.', 'I can provide my passport, I-94 and approval notice for the I-9.']],
        'terms' => ['n' => 'Technical terms', 's' => ['Kubernetes orchestrates containers across a cluster.', 'The service is idempotent, so a retry is safe.', 'We use asynchronous processing with a message queue.', 'PostgreSQL and Snowflake are our main databases.', 'Authentication uses OAuth with JSON web tokens.', 'The pipeline runs unit tests before every deployment.']],
    ];
}
